### ISSUE TITLE
Ozone mail

### ISSUE THREAD

**Issue by mihai-macaneata** [eaudeweb/ozone#1009]
Frontend part implemented on branch OzoneMail

**Comment by mihai-macaneata** [comment]
https://github.com/eaudeweb/ozone/tree/OzoneMail

**Comment by catalinjitea** [comment]
Backend part done and merged into develop. @mihai-macaneata please integrate frontend with backend.

To retrieve the list of available email templates: GET `/api/email-templates/`.

To retrieve the list of available emails within a submission (conversation history): 
GET `/api/submissions/<submission_pk>/email/`.

To send an email: POST `/api/submissions/<submission_pk>/email/` with the following request body:
```
{
	"subject": "Test",
	"from_email": "from_test@email.com",
	"to_email": "to_test@email.com",
	"cc": [
		"cc1@email.com",
		"cc2@email.com"
	],
	"body": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis eveniet eaque iusto perspiciatis autem ex eum"
}
```

**Comment by melish** [comment]
NB! The UI should be visible only for Secretariat.

**Comment by melish** [comment]
Remaining:
- use the same widget for To and Cc (there can also be multiple recipients in the To field).
- rename the button "Ozone mail" to "E-mail"
- Show the "Correspondence" tab after a new email is sent
- Use a better placeholder in the To and Cc input fields, e.g. "Type the recipient address and press enter"
- Prefill the "To" address with the E-mail field from submission info
