### ISSUE TITLE
Process Agents - uses, reports & related tables

### ISSUE THREAD

**Issue by sorinstelian** [eaudeweb/ozone#1016]
Remaining: UI for Process agent forms.
Blocked by #1083 and #1084

**Comment by sorinstelian** [comment]
Assigning @mihai-macaneata as this should now be done in frontend.

**Comment by melish** [comment]
related to #1083 and #1084

**Comment by mihai-macaneata** [comment]
56e6b4cad8159e4e19dd6308fb51b91246cc055a

**Comment by melish** [comment]
Remaining: to improve the usability of the admin form for process agent uses reported, now it's too cumbersome to use:
http://prntscr.com/olglps

**Comment by sorinstelian** [comment]
Opened https://github.com/eaudeweb/ozone/issues/1461 for remaining issues; closing this one.
