### ISSUE TITLE
Transfers - remarks are not imported

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#1042]
There are two types of remarks which we should capture:
- ProdTransfers.Remark
- Letters.Remarks (which are sometimes relevant, see LetterID=10003)

Not sure in which model/field the second one belongs. In principle I could ask the secretariat to exclude this remark from the data migration and only use the first one - please check.

related to #925

**Comment by sorinstelian** [comment]
It looks like Letters.Remarks is actually imported into the submission's `transfers_remarks_secretariat` field (not on the Transfer objects, but on their source Submission). I think that a small tweak in the UI would make the field visible in the submission.
