### ISSUE TITLE
Improve the usability of the UI for transfer-submission relation

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#1045]
It's difficult to find the right submission when entering *new* transfer records in Django admin.

Some sort of browse/picklist/filtering should be implemented (at least by source/destionation party and period).

For the moment the workaround is a two-step save - first without the related submissions, then the list becomes filtered.

**Comment by melish** [comment]
Also related to the "reporting period" issue - see https://github.com/eaudeweb/ozone/issues/925#issuecomment-500928474_

**Comment by sorinstelian** [comment]
> Also related to the "reporting period" issue - see [#925 (comment)](https://github.com/eaudeweb/ozone/issues/925#issuecomment-500928474)_

There is no filtering done on the reporting period to match that of the related submissions; it can be selected freely. I think that's OK, as parties may do the reporting in other periods than those in which the actual transfers took place.

**Comment by melish** [comment]
Ok, let's close this until further comments
