### ISSUE TITLE
Transferred amount should be mandatory

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#1046]
Otherwise an error occurs when entering a new transfer in django admin:
  File "/var/local/ozone/ozone/core/models/transfer.py", line 108, in populate_aggregated_data
    aggregation.prod_transfer += self.transferred_amount * potential
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

Also - please check for rounding/float precision issues the calculation of aggregation.prod_transfer (see also api.export_pdf.util.sum_decimals)

**Comment by sorinstelian** [comment]
Created https://github.com/eaudeweb/ozone/issues/1051 for the rounding precision part
