### ISSUE TITLE
Rename "Add substances" green button to "Validation" when the form is read only

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#1065]
i.e. when adding substances is not allowed

also - replace the "Edit" icon with a "view only" icon (eye?) when appropriate (i.e. when user can't make any changes in the modal dialog).

**Comment by mihai-macaneata** [comment]
If form is read only and there are no errors I think it should be better to hide the sidebar

**Comment by mihai-macaneata** [comment]
also - replace the "Edit" icon with a "view only" icon (eye?) when appropriate (i.e. when user can't make any changes in the modal dialog).
