### ISSUE TITLE
Transfers and RAF - "Valid" flag should not be visible

### ISSUE THREAD

**Issue by sorinstelian** [eaudeweb/ozone#1067]

**Comment by sorinstelian** [comment]
Right now it is visible (but has no UI to set it). I'm not sure whether it should be used, don't see a very good reason for it.

**Comment by melish** [comment]
According to the latest suggestions from OzSec, we will not display the "Valid", nor "Approved" flags for Transfers and EUN/CUN (exemptions)

**Comment by melish** [comment]
similar to #1071

**Comment by mihai-macaneata** [comment]
a32a4d58df075890e59ff8c3626bd1abdb38e42c
