### ISSUE TITLE
Update model (Country vs parent Party) and related tables 

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#107]
- Import, Export etc
- this will affect the primary key (multiple rows for the same substance and party - but different countries).

**Comment by melish** [comment]
we decided to leave the import/exports/etc as they are (maybe just rename columns source_party  and destination_party to source_country and destination_country, respectively).

**Comment by sorinstelian** [comment]
For now we will keep the fields as they are, we will just take parent_party into consideration when calculating values for the derived/aggregated tables.

**Comment by melish** [comment]
Implemented in Party,get_main_parties. Will have to remember to consider this choice when calculating the derived data.
