### ISSUE TITLE
Art 7 - Imports and Exports - Don't reset amounts when a single country is selected

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#1080]
... when pressing the "Add 1 rows" button in the party multiple select.

When adding 2 or more rows, resetting amounts is ok.

TODO: how to prevent losing the selected party when the form is saved, but "Add x rows" button not pressed?

**Comment by mihai-macaneata** [comment]
You teach the users how to use the app

**Comment by mihai-macaneata** [comment]
c3fe193704d390f4597af8b90cd77df4a2fededb
