### ISSUE TITLE
Process agents uses - model issues

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#1084]
issues:

- ProcessAgentContainTechnology should not be related to Submission

- ProcessAgentUsesReported does not need to be directly related to ProcessAgentUsesValidity. In fact, ProcessAgentUsesValidity should rather be called ProcessAgentApplicationValidity
- ProcessAgentUsesReported - missing relation to ProcessAgentApplication (relation should be created based on decision and ProcessAgentUsesReported.process_number == ProcessAgentApplication.counter)

- expand ProcessAgentUsesReported.ProcessAgentUses and validity in API serializers (to be able to show substances and name of application in UI).

**Comment by sorinstelian** [comment]
We decided that:
- `ProcessAgentContainTechnology` becomes a lookup table. a `contain_technology` field in `ProcessAgentUsesReported` will be a foreign key to it.
- ProcessAgentUsesReported does not need to be directly related to ProcessAgentUsesValidity. In fact, ProcessAgentUsesValidity should rather be called ProcessAgentApplicationValidity
- `process_number` has no place in `ProcessAgentUsesReported`; it will be a FK to ProcessAgentApplication
- API should show all relevant data
