### ISSUE TITLE
RAF - breakdown of quantity_used by category

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#1110]
To clarify: What is quantity_used (vs production and imports).
Are there any validation rules for data entry?

**Comment by melish** [comment]
Validation rules continued on #1166

Breakdown by category to be implemented using a default category_unspecified (which will be added to individual amounts by category, to obtain the total_used for critical uses).

**Comment by sorinstelian** [comment]
Added a "Other" category in mkfixtures (25c2543b0e326a6968628b42209bca2ec27d0aac).

**Comment by sorinstelian** [comment]
Added a special code (9999) for Other/Unkown party in 36f4b5b14a960b8d828e434507cc4f4d2347191d. This will be interpreted by the serializer and translated to None in the actual model instance, to avoid creating a "special" party in the DB.
