### ISSUE TITLE
Old js and css cached by the browser after redeploy

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#1127]
the index.html is cached, pointing to the old versions of the web application => load error and https://sentry.io/organizations/eaudeweb/issues/989296615

we should prevent the caching or reduce the max cached time of the main index file.

Strangely it works (not always, but most of the times), when opening directly /reporting/dashboard.

Maybe only in ozone.edw.ro (Apache, shared with other websites)? In ors.ozone it seems ok.

Apache conf: https://gist.github.com/melish/aa9635698444f0a4a05264fef5d8af19
nginx conf ozone-staging: /etc/nginx/conf.d/default.conf

**Comment by mgax** [comment]
This highly-upvoted StackOverflow [answer](https://stackoverflow.com/a/2068407) says we should set the following header: `Cache-Control: no-store, must-revalidate` (unless we care about IE6 and super-outdated http proxies).

**Comment by mgax** [comment]
For nginx on ozone-staging I've changed:

```diff
-expires 1d;
+add_header Cache-Control "no-store, must-revalidate";
```

**Comment by mgax** [comment]
For Apache we should add:
```apache
Header set Cache-Control "no-store, must-revalidate"
```

**Comment by melish** [comment]
> 
> 
> For Apache we should add:
> 
> ```apache-config
> Header set Cache-Control "no-store, must-revalidate"
> ```

Added, we'll see what happens after next stable release.

**Comment by alexkiro** [comment]
FWIW, you can have custom cache config for `/index.html` only in nginx, instead of disabling caching for the whole application, by adding something like:
```
  location = /index.html {                                                                                                                                                                                             
    expires -1;                                                                                                                                                                                                      
  }           
```

This should resolve the issue, as the other files of the web application have hashed filename, forcing re-download when a new version appears.

**Comment by mgax** [comment]
> the other files of the web application have hashed filename, forcing re-download when a new version appears

Ah, groovy. So indeed we only need to disable caching for `/index.html`. I'll make a PR.

**Comment by mgax** [comment]
@melish I think the issue is resolved, does it still happen on any environment?

**Comment by melish** [comment]
Probably not. I'll reopen in case I notice something
