### ISSUE TITLE
RAF import for same substance and multiple source countries

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#1159]
Check UA/2003 submission vs source data:

![image](https://user-images.githubusercontent.com/1218168/61848094-9e520600-aeb5-11e9-8bb1-1ea080db660c.png)

![image](https://user-images.githubusercontent.com/1218168/61848560-2e447f80-aeb7-11e9-9979-975a4cb261e9.png)

![image](https://user-images.githubusercontent.com/1218168/61848583-44524000-aeb7-11e9-9592-bca9b38986e7.png)

This causes some errors during revise and other operations:

    raise ValidationError(_(f"Duplicate value for {field_value}"))
django.core.exceptions.ValidationError: ['Duplicate value for (<Substance: CFC-11>, False)']
Unprocessable Entity: /api/submissions/1754/raf/

**Comment by melish** [comment]
To test also: Australia, 2006 (critical uses)

**Comment by sorinstelian** [comment]
Fixed in e024b946246ebebec19e1339e3024ad6e5713467
