### ISSUE TITLE
Exemption nominations and approval - read only for parties

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#1172]
Countries should not be able to use the data entry webforms for EUE/CUE nominations and EUE/CUE approvals – they should only be able to submit files.  Only Secretariat should be able to enter the numbers.  Currently, when logged in as Kenya, we can enter EUE/CUE nominations and EUE/CUE approvals as Kenya.

**Comment by sorinstelian** [comment]
Backend permissions are correct as of d02df5e4931bb8ee283e420c19bd43b4b559eeaa

**Comment by sorinstelian** [comment]
Even though it is possible to enter nomination data in the UI as a party, and the data appears to be saved, the data is not actually sent to the `submission/<pk>/exemption-nomination` endpoint, and on refresh it is lost.
