### ISSUE TITLE
Process button doesn't work anymore

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#1197]
(tested on Art7 form).
It seems to do a Save, but doesn't change the state of the submission.

Also: it should not go back to the dashboard, but keep the current submission open (it may be reloaded, if necessary).

**Comment by mihai-macaneata** [comment]
Can't reproduce. Probably fixed by b6149e9bd7ecfceb34125f67a596c5c1d6cc1aa3

**Comment by melish** [comment]
probably yes
