### ISSUE TITLE
Changes in modal for selecting countries in Art7 form

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#1233]
- [x] after selecting several countries in the dropdown list, users have to press "Add rows" twice (one for focusing out of the dropdown, second to trigger the action).
Can it work in a single click?

http://prntscr.com/owjlln

- [x] Add an explanatory text in the title of the dialog and in the placeholder: "Select one or more countries"

http://prntscr.com/owkkpx

Use this text: "Select one or more countries/regions/territories"

- [x] Rename the "Add rows" button, see #1232

**Comment by mihai-macaneata** [comment]
Maybe

**Comment by mihai-macaneata** [comment]
Probably
