### ISSUE TITLE
Another 'Close' button in the edit row modal dialog

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#1234]
In the Art7 form, the modal to view/edit rows in full mode is quite long and the "Close" button below is not initially visible.
Please add another 'Close' button in the top area, with the same functionality.

**Comment by mihai-macaneata** [comment]
something like this ? 
![image](https://user-images.githubusercontent.com/12417029/63653298-8949ea80-c773-11e9-97f7-9c14ede446e3.png)

**Comment by melish** [comment]
Cred că mai degrabă unul verde pe care să scrie Close, cum e cel de jos
