### ISSUE TITLE
Calculated amounts small changes

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#1235]
- [x] Hide the BDN columns, they are not very relevant nowadays and distract the user
- [x] right align the numbers
- [x] make the vertical lines for the main groups (Production, Consumption) more visible

**Comment by melish** [comment]
Some lines missing after bootstrap upgrade
http://prntscr.com/p7qw41

**Comment by razvanMiu** [comment]
https://github.com/eaudeweb/ozone/pull/1295
