### ISSUE TITLE
New party columns - Non-Art5 * groups for Annex F

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#124]
in PartyHistory

Belarus, Kazakhstan, the Russian Federation, Tajikistan and Uzbekistan

**Comment by sorinstelian** [comment]
@melish : for now, the only change in the PartyHistory model is that "Non Article 5 Group 1" and "Non Article 5 Group 2" have been added as options for the party_type field. Fixtures for PartyHistory have also been created.

**Comment by melish** [comment]
This is fixed already
