### ISSUE TITLE
Expanding blends doesn't work in Art7 

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#1284]
http://prntscr.com/p7r08e

Same for Destruction, Imports, Exports tabs

Possibly related: In Imports and Exports, when clicking on "Add countries", the following error appears in the console:

[Vue warn]: Invalid prop: type check failed for prop "placeholder". Expected String, got Boolean with value false.

- [x] add E2E tests
- [x] fix the bug

**Comment by razvanMiu** [comment]
https://github.com/eaudeweb/ozone/pull/1288
