### ISSUE TITLE
Separate uploads by public and private

### ISSUE THREAD

**Issue by sorinstelian** [eaudeweb/ozone#1293]
Related to #1292

**Comment by mgax** [comment]
Conclusion: we make `MEDIA_ROOT` private by default and create a `/public` folder inside which is served without authentication as public files. Country profile files will live in this public folder, while submissions will not, and they must be accessed via the submissions API.

**Comment by mgax** [comment]
I'm leaving the issue open for a bit more, to update the nginx/apache config for all deployments.

**Comment by mgax** [comment]
Ok, `ozone-staging.edw.ro`, `ozone.edw.ro` and `ors.ozone.unep.org` are up to date with only serving public media from nginx or apache.
