### ISSUE TITLE
Sentry error related to file upload

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#1309]
SuspiciousFileOperation
Storage can not find an available filename for "submissions/2018/Article 9 - Research, development, public awareness and exchange of information/BJ/1/VC_Rules_of_Procuedure_pLr1YoD.pdf". Please make sure that the corresponding file field allows sufficient "max_length".

`# Entire file_root was truncated in attempt to find an available filename.`

**Comment by mgax** [comment]
Could you please add a link to sentry?

**Comment by melish** [comment]
https://sentry.io/organizations/eaudeweb/issues/1239157354/
