### ISSUE TITLE
baseline_bdn in prodcons

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#1319]
Is not always the value given by Baseline(type = 'BDN_NA5').

- in most cases, the BDN baseline is the A5 or NA5 Prod baseline
- for NA5 parties, year >= 2000, for annex groups A/I, A/II, B/I and E/I, it's the BDN_NA5 baseline

(Note: for year 2000, in the above cases, the limit is a combination of NA5Prod and BDN_NA5. We ignore this case and use BDN_NA5 baseline for year 2000, as well)

See aggregation.py -         # Populate baselines; first get appropriate baseline types

**Comment by sorinstelian** [comment]
AFAIK it is used in the Production/Consumption section of the ORS dashboard.

**Comment by melish** [comment]
I think it's safe to hide it from the dashboard and if nobody complains, remove it from prodcons as well.
