### ISSUE TITLE
Legacy xlsx export only for selected submissions

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#1330]
Can this work? I think it would be useful.

Related to #1215, #1258

![image](https://user-images.githubusercontent.com/1218168/65815040-a64e5f00-e1f2-11e9-87f9-266500fa18ca.png)

**Comment by mgax** [comment]
You mean that the export should only cover the submissions you select from the checkboxes? But that's exactly how it already works. Django Admin creates a queryset from the checkbox selection and passes it on to the action function. And the xlsx export code was always designed to generate an xlsx using a `Submission` queryset as starting point.

**Comment by melish** [comment]
Cool, closing this issue.
