### ISSUE TITLE
Country_ID UNK in ImportNew and Exports

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#137]
can't we replace with a NULL value?

**Comment by sorinstelian** [comment]
Already did that as part of the solution for https://github.com/eaudeweb/ozone/issues/125

**Comment by sorinstelian** [comment]
@melish : can we close this?

**Comment by melish** [comment]
waiting for the migration of submission tables

**Comment by melish** [comment]
Actually, the migration will fail if country_id is UNK, so I'll close this
