### ISSUE TITLE
Can we record the username in Sentry errors?

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#1386]

**Comment by sorinstelian** [comment]
As can be seen [here](https://sentry.edw.ro/eaudeweb/ozone/issues/2266/) or [here](https://sentry.edw.ro/eaudeweb/ozone/issues/2268/), exceptions raised by Django do have the username captured. Checking to see whether there are any unhandled cases.

**Comment by melish** [comment]
Maybe the username is present only for backend exceptions. See this one: https://sentry.edw.ro/eaudeweb/ozone/issues/2302/
