### ISSUE TITLE
Improve speed of calculate_baselines and calculate_limits

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#1396]
see  ozone/core/calculated/baselines.py and limits.py
It takes forever to recalculate all baselines, probably because of too many SQL queries.
Maybe all data could be pre-loaded and processed from memory.

For instance, when recalculating baselines for a single party and a single annex group, out of 470 db queries there are about 80 queries from baselines, 80 from limits, 150 from party/party_history (including several for parties CN - see is_china_or_brazil or is_european_union - executed 20 times)

**Comment by sorinstelian** [comment]
Fixed in #1423
