### ISSUE TITLE
Use component_name instead of substance_name when working with blends

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#140]
related to #122

when creating a custom blend, users should be able to enter a new component_name in addition to picking one substance from the list ("taggable field")

**Comment by mihai-macaneata** [comment]
Frontend part is done. Will check if everything works after the api modifications are ready

**Comment by melish** [comment]
When adding a custom blend using existing substances, the name of the substance should be shown in the data entry form when expanding the blend:

![image](https://user-images.githubusercontent.com/1218168/49029795-31fbf700-f1ae-11e8-904c-829f990873b7.png)

**Comment by sorinstelian** [comment]
Closed by e3b0a1327a4592b87db9bc97b299c584a7100c2e
