### ISSUE TITLE
Focal points - address fields

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#1404]
Add more fields to the focal points model:

- organization
- city
- country 
- address

What is currently stored into the address field will be migrated to the new "organisation" field.
The initial import (import_country_profile_data should also be updated to reflect the above).
The API as well - and when done, we need to coordinate with the website team to use the new "organisation" field instead of the old "address"

**Comment by mgax** [comment]
> The API as well - and when done, we need to coordinate with the website team to use the new "organisation" field instead of the old "address"

We could provide both fields until they get a chance to deploy their update.

**Comment by melish** [comment]
Or we can keep the current data in both fields (address + organisation), add all fields in the API, then remove it later once they have deployed the update.

**Comment by mgax** [comment]
> Or we can keep the current data in both fields

I assume you're suggesting we keep data in both DB tables. That violates the "single source of truth" principle and makes it harder to follow the logic.
