### ISSUE TITLE
Baseline prod/cons report for NA5 parties (C/I)

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#1414]
rpt-25-na5-1989-baseline-hcfc

Similar to #1338, but using a vertical layout, because the formula is simpler.
Maybe we can reuse the same layout, though

**Comment by mgax** [comment]
The sample report `rpt-25-na5-1989-baseline-hcfc` contains values from the AI NA5Prod and NA5Cons baselines even though the columns are marked "CI baseline". The PR uses values from "CI" though.
