### ISSUE TITLE
File upload error

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#1450]
An exception occurs when trying to upload files in tusd: UPLOAD denied: INVALID TOKEN
https://sentry.edw.ro/eaudeweb/ozone/issues/2897

From tusd logs:
```
usd_1              | [tusd] 2019/11/21 08:09:26 event="RequestIncoming" method="POST" path=""
tusd_1              | [tusd] 2019/11/21 08:09:26 event="HookInvocationStart" type="pre-create" id=""
tusd_1              | [tusd] 2019/11/21 08:09:26 event="ResponseOutgoing" status="400" method="POST" path="" error="pre-create hook failed: endpoint returned: 400 Bad Request"
tusd_1              | [tusd] 2019/11/21 08:09:26 event="HookInvocationError" type="pre-create" id="" error="endpoint returned: 400 Bad Request"
```

This may be related to some relatively recent changes in tusd itself. I had to replace also the `-dir` parameter with `-upload-dir` to make tusd start. It was renamed here:
https://github.com/tus/tusd/commit/d2be5e82bd7de4372b52399f8f9653ab72e05f78

**Comment by sorinstelian** [comment]
Fixed in 2c66327c09eeb4dfbae0bc8fe5af296f99280c0d and af926c24d9dc371b5b1954915db8ec384e378649
