### ISSUE TITLE
Obligation - Reporting Period mapping

### ISSUE THREAD

**Issue by sorinstelian** [eaudeweb/ozone#148]

**Comment by sorinstelian** [comment]
Makes sense, given that the mapping would not have a lot of items anyway and the users will generally pretty much know what they have to do.

**Comment by melish** [comment]
Yes, it makes sense. For instance, for EssenCrit ( RAF), the period depends on a pre-existing decision (exemption).
For HAT -> only applies to parties which have previously informed the Secretariat that they want to report on it

**Comment by melish** [comment]
See also #259
