### ISSUE TITLE
Add "flags" tab on the Art. 7 form

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#160]

**Comment by sorinstelian** [comment]
Flags are as follows:
- provisional (per submission)
- superseded
- complete (per annex group & tab)
- blanks: Has Blanks, Confirmed_Blanks
    - (only for the secretariat, when dealing with a new submission)
    - not applicable for online submissions, only for those received through hardcopy (which the Secretariat has to then enter in the system)
    Blanks -> if there are blanks
    Confirm_Blanks -> if the party has confirmed that blanks are zeroes

**Comment by mihai-macaneata** [comment]
What state should the submission be in when when each type of the flag can be set, because it seems that some of them should be set during data entry and other after, maybe ?
Can you specify some details about this ? @melish

**Comment by mihai-macaneata** [comment]
@sorinstelian The flags should be in a flags object in api/submissions/pk. 
Maybe even a hyperlinked endpoint like the ones for the tabs data. But first we need to know the exact structure of all flags in order to determine if it's needed

**Comment by melish** [comment]
>     * complete (per annex group & tab)
> "per annex group": At the moment, the user doesn't clearly see the annex group in the interface so this
> flag makes no sense. An option would be to add a Group column in each table. Should we do this ?

No. Users should be familiar enough to the annex/groups by substance name.

> Do we want a way to specify the exact location of a blank (tab -> row -> field)
> or do we want a way to mark a tab as "has blanks"

Exact location is not necessary. Only one flag for the entire form is enough.

> What state should the submission be in when when each type of the flag can be set, because it seems > that some of them should be set during data entry and other after, maybe ?
Flags should be visible and set by the OzSec only in any state.
Flag "provisional" must be accessible (r/w) by reporters only in Data Entry state.
Flag "superseded" is set only automatically and read-only to all roles.

**Comment by melish** [comment]
Flag | Art 7 | HAT | EssenCrit | Letter | Visible to | Updateable by/in | Changed when | Default value | Label | Notes
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Superseded | Y | Y | Y | N | all roles | Backend (in all states exept   Data Entry) | A version enters the   "Submitted" state.          The flag is set on all the other versions for the same   party/period/obligation except for those in Data Entry state. | FALSE | Superseded |  
Provisional | Y | Y | Y | Y | all roles | Party (in Data Entry),     OzSec (in all states) | On demand, during data entry (by   party) and anytime by OzSec | FALSE | Provisional | Used when the party is unsure   that the information is accurate and they expect some changes in the reported   data (e.g. they were based on estimations which are still to be confirmed).
Checked_blanks | Y | Y | N | N | OzSec | OzSec (in all states) | OzSec enters data received   through another channel (e.g. paper) and checks for blanks in a second step | TRUE | Checked blanks | Also to keep track of historical   information (even if we may not use this field anymore)
Has_blanks | Y | Y | N | N | OzSec | OzSec (in all states) | OzSec enters data received   through another channel (e.g. paper) and rows without any quantity field are   found | FALSE | Has blanks |  
Confirmed_blanks | Y | Y | N | N | OzSec | OzSec (in all states) | After OzSec receives the   confirmation from the Party that the blanks are zeroes. | FALSE | Confirmed blanks |  
Has reported | 10 checboxes:     A1,A2,     B1,B2,B3,     C1,C2,C3     E,F | 1 checkbox (only F) | N | N | all roles | Party (in Data Entry),     OzSec (in all states) | When a party chooses not to   report for one annex group - because they don't want to report or to indicate   that the information is not complete. | TRUE for all annexes except Annex   F | Annex groups that have been   reported in full | The ultimate purpose of these   flags is to know whether to calculate or not production and consumption and   what to do with the derived numbers.                    These flags are indirectly related to the answers to questionnaire (we may   add in the future some warnings/confirmations depending on the choices, if   the submission is not provisional).          Note: there is a single flag for both F1 and F2 annex groups.

**Comment by sorinstelian** [comment]
@mihai-macaneata : added nested object with all flags on submission.: `api/submissions/<id>/submission-flags`.
To see which flags are changeable, you can use field `changeable_flags` from submission detail.
