### ISSUE TITLE
Flags to identify status of reporting period

### ISSUE THREAD

**Issue by sorinstelian** [eaudeweb/ozone#168]
The following flags should be added to the `ReportingPeriod` model:
- `is_reporting_allowed` - indicates whether reporting can be performed for this reporting period. default True, will be False for baseline years.
- `is_reporting_open` - indicates whether reporting is open/ongoing for this reporting period. Please note that several periods could be open at a given time. Submissions from open periods can be cloned freely. default False, will be set to True by Secretariat through the Admin interface when a reportig period opens.

N.B.: It is perfectly possible to report for any period that has `is_reporting_allowed == True`; `is_reporting_open` only indicates that the period is "current".

Changes for this should cover:
- models (incl. validation logic for cloning & checks for new submissions)
- fixtures
- admin interface
- API
- user interface

**Comment by sorinstelian** [comment]
Also described in https://github.com/eaudeweb/ozone/issues/167

**Comment by catalinjitea** [comment]
@mihai-macaneata backend part is done.
