### ISSUE TITLE
Import and Export of Polyols

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#169]
We need to capture one new type of quantity in imports and exports.

ImpPolyol and ExpPolyol will capture amounts reported as either imports or exports as polyols – these are currently recorded in comments but we are working to extract the figures and record them in a field of their own.  Their behavoiour is that they should not be part of the “Total” – hence they do not need to be part of the validation on the Total.  In terms of presentation in reports, they could be added as a separate row labeled “HCFC-141b contained in preblended polyols”.  In terms of data entry screen, they should be included in the fields under "Quantity of new substance imported/exported for exempted essential, critical, high-ambient-temperature or other uses".  In terms of storage in the DB, they can be a column/field in the relevant tables.

The field will only be visible when entering data for CFC-11 and HCFC-141b (pure).  These are the only two substances we are aware of that have been reported under Article 7 as contained in pre-blended polyols.  The field will not appear for other substance and blends – Until/unless we learn of other specific substances or blends that are used in a similar manner (i.e. blends contained in polyols), and then we would display the field for those specific substances/blends.

The idea is that the CFC-11/HCFC-141b contained in preblended polyols will not be part of the Totals in columns 3 nor 4 – hence will not be used in the validation rules of those totals.  And for consistency in the screen display – the polyol quantity should be excluded from the total of column 6.  However, the polyol quantity could be displayed (included) in the mouseover message that displays when the mouse hovers over the column 6 – maybe in brackets.

**Comment by melish** [comment]
Field quantity_polyols can be added to Article7Import and Article7Export (not Production).
We will update the data entry forms afterwards

**Comment by sorinstelian** [comment]
@mihai-macaneata @melish : What we can do in the backend is to not allow quantity_polyols to be non-null for entries related to substances that have `is_contained_in_polyols == False`. Do you think more than that is needed?

**Comment by melish** [comment]
No. In fact, I think it may be enough just to hide them in the frontend for other substances and avoid too many constraints in the backend. But there is always the issue of potential reporting via API instead of web forms... so let's do as you said

**Comment by sorinstelian** [comment]
Solved in https://github.com/eaudeweb/ozone/pull/316.

**Comment by melish** [comment]
We still need to add these fields in the frontend

**Comment by melish** [comment]
Please add the field quantity_polyols in Import and Export tabs, as described below:

- these fields should be added in the modal with additional quantity fields, but only for certain substances (CFC-11 and HCFC-141b) and blends containing such substances. Use the new field `is_contained_in_polyols` from /api/substances to determine when to show/hide the field
- label: "Polyols". A more detailed tooltip to be added later, please use for now "Quantity contained in preblended polyols"
- these fields should not be included in the calculation of total quantity (column 6) and neither in any validation (e.g. we could have a row with zero total quantity and >0 polyols)
- however, do show them in the tooltip shown for columns 6 and 7 (if possible, enclosed in brackets)
