### ISSUE TITLE
When identifying non-parties for a substance, how do we take date into account?

### ISSUE THREAD

**Issue by sorinstelian** [eaudeweb/ozone#173]
I believe we should identify the parties that had not ratified, at the start of the reporting period, the treaty controlling that specifc substance. Is that correct? Should it be at the end of the reporting period? Do we ignore this for now? :)

This is needed for the get_non_parties endpoint.

**Comment by melish** [comment]
In theory, it should be the beginning of the reporting period. If one country becomes a party during the reporting period, other parties should be allowed to report trade with that country. In reality, the actual date of the trade is compared to the date of entry into force (outside the system) and only trades before the EIF date are normally reported.

Additional info: see #269
For different substances, there are different start dates for restrictions on trade with non-Parties.  These are spelt out in paragraphs 1 and 2 (together with the bis, ter, etc) of Article 4 of the protocol: Control of trade with non-Parties. For HFCs, the restrictions start from 2033.

However, there are various political issues with implications to the country select list in Data Form 5 (e.g. sometimes territories are not included in ratifications).

Most likely we will show all parties and territories in the list (except for Czechoslovakia and Unknown, which will be completely deleted from the Party table). There will be another ticket for that.
