### ISSUE TITLE
QPS field should only be visible for Annex E substances

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#194]
This rule includes the data entry field from the additional edit dialog.
QPS = Quarantine and pre-shipment applications

**Comment by mihai-macaneata** [comment]
28da449a15dbda6e4eece0b897e37b2a4535c83d

**Comment by mihai-macaneata** [comment]
Substance part is done. There is more that need to be discussed for the blends part

**Comment by sorinstelian** [comment]
As discussed with @melish, for blends we will consider that any blend containing an annex E substance can be used for QPS.

**Comment by sorinstelian** [comment]
Substance & blend `is_qps` flag added in f83c0f21963782565823a57b6f6a0e373ef10d78

**Comment by mihai-macaneata** [comment]
when posting a new custom blend in /blends, the response contains all the fields regarding that blend except the is_qps field. 
After fetching again the blends list, the previously created blend has the field.

**Comment by sorinstelian** [comment]
After 6e2fa13fb6b273be71d20272aef5c2a0d6459d25, `is_qps` is included in `create` response for custom blends.
