### ISSUE TITLE
Custom blends - uncontrolled substances

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#195]
When creating a custom blend, uncontrolled substances (no Annex/Group) should be included in the list for selection. Ideally show them after the controlled substances (maybe use grey text if possible)

**Comment by sorinstelian** [comment]
As discussed with @mihai-macaneata , the `group-substances/` endpoint should also return a "non-controlled" (or similar) key, with its value being a list of non-controlled substances.

**Comment by sorinstelian** [comment]
eccfb21b917f8817030e5ba8af31436e01961f8e - Added an "uncontrolled" key in the endpoint response for now.
