### ISSUE TITLE
Notifications ("Please submit your report for ...") => also for past periods

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#198]

**Comment by sorinstelian** [comment]
Implementation-wise, this requires an endpoint that returns an obligation - reporting period mapping containing all `is_reporting_allowed` reporting periods for which there is no "current" submission (exact specs TBD).

**Comment by sorinstelian** [comment]
Seems related to #438 , which has been filled out in more detail.

**Comment by melish** [comment]
To be continued on #438
