### ISSUE TITLE
Hide Clone button in dashboard for state=data_entry

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#201]

**Comment by sorinstelian** [comment]
@mihai-macaneata : for this, you can use the `data_changes_allowed` flag, which is (could be in the future? :) ) more general than comparing with the state.

**Comment by sorinstelian** [comment]
Actually, on second thought, an `is_cloneable` flag would be more appropriate - and useful in all states.

**Comment by sorinstelian** [comment]
`is_cloneable` flag added in 9635871cde9959dead5bc97aebbf28171511f288

**Comment by sorinstelian** [comment]
Indeed. This may be due to unclear/verbal specs that we did not put in writing. :)

I have solved the immediate part of this issue in ccbaa7cc3029b5a7e2d115b172b4b50b9d3c39e3

Will also document the current behavior in an analysis issue to make sure it is as expected.
