### ISSUE TITLE
Filter list of parties in tab Non party trade

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#207]
using the new API for non-parties 

Note: Islands (territories dependent on a non-party) should remain included in the list.

**Comment by melish** [comment]
Possible some refactoring necessary to the current API (/api/get-non-parties/$substance_id) to improve front-end performance.
- either include all annexes/groups in a single request (e.g. /api/get-non-parties)
- or replace $substance_id with $group_id, so we have less requests and cache them

**Comment by sorinstelian** [comment]
Response format as requested by @mihai-macaneata :
```
{
    group_id_1: {
        party_id_1: True,
        party_id_2: True,
        ...
    },
    group_id_2: {
        ...
    }
}
```
(N.B.: no need for False values)

**Comment by sorinstelian** [comment]
Related to https://github.com/eaudeweb/ozone/issues/208

**Comment by sorinstelian** [comment]
@catalinjitea : Please note the initial note in this issue:
`Note: Islands (territories dependent on a non-party) should remain included in the list.`

I think that in `get_non_parties()`, when building `signing_party_ids` we should also include the parties that have a parent party that has ratified that treaty.

**Comment by sorinstelian** [comment]
Looks completely fixed in both backend and frontend, moving to testing.

**Comment by melish** [comment]
As recently clarified, we might have to revert this change
