### ISSUE TITLE
Validations for Destruction, Non-Party and Emissions tabs

### ISSUE THREAD

**Issue by sorinstelian** [eaudeweb/ozone#212]
Destruction
----

* [x] the quantity destroyed field is the only mandatory field.
* [x] Please see why the comments (OS and party) are missing from this tab

Emissions
----
* [x] Facility name (column 1) and generated emissions (column 6) are mandatory
* [x] If either one of columns 3a, 3b, 3c is filled in, then 3a must be >= 3b + 3c
* [x] if there are values in all these fields (2, 3a, 4, 5, 6) then 2 must be equal to 3a+4+5+6
* [x] if not all of (2, 3a, 4, 5, 6) have values, then 2 must be >= to 3a+4+5+6
* [x] Fix typo : Ammount (in validation message). Should be Amount

Non-party
----
* [x] Either one of 4, 5, 6, 7 should be filled in
* NB: column 3 is optional

**Comment by melish** [comment]
related to #81

**Comment by mihai-macaneata** [comment]
The validations here are different from the ones in #231 . Ar the validations listed here still valid ?
@sorinstelian @melish
