### ISSUE TITLE
Take user permissions into account at state change and cloning (including is_cloning and available states)

### ISSUE THREAD

**Issue by sorinstelian** [eaudeweb/ozone#226]

**Comment by melish** [comment]
Is this issue stuck and you need my support?

**Comment by sorinstelian** [comment]
Not stuck, Catalin was waiting for specs from me on who can perform transitions, working on it.

**Comment by sorinstelian** [comment]
### Transitions - roles mapping (who can perform which transitions):

**Data Entry - Submitted**
- Party-write user from Party to which the submission refers to, *only if* the submission was started by the Party
- Secretariat-write user, *only if* the submission was started by Secretariat

**Any state - Recalled**
- Secretariat-write user, *only if* the submission was started by Secretariat
- Party-write user from Party to which the submission refers to, *only if* the submission was started by the Party

**Recalled - Any state**
- Secretariat-write user, *only if* the submission was started by Secretariat
- Party-write user from Party to which the submission refers to, *only if* the submission was started by the Party

**Submitted - In Processing**
- Secretariat write user

**In Processing - Finalized**
- Secretariat write user
