### ISSUE TITLE
Add is_eu_member, is_high_ambient_temperature and is_a5 to  /api/get-party-ratifications

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#233]
These fields are needed for #210

We only need the "current" value in the api - i.e. values from PartyHistory matching the reporting period.
Ssuggestion: add a current class method in Reporting period:
```
@classmethod
    def current(cls):
        today = datetime.now().date()
        return ReportingPeriod.objects.filter(
            start_date__lte=today,
            end_date__gte=today,
        ).first()
```

**Comment by sorinstelian** [comment]
^ not waiting for #234 anymore; in progress

**Comment by sorinstelian** [comment]
Actually I think [my previous comment](https://github.com/eaudeweb/ozone/issues/233#issuecomment-446231610) is wrong, it looks like this endpoint will be used only for lookup tables.
