### ISSUE TITLE
Use sort_order and type when showing blends in selection list

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#235]
* [x] order by sort_order asc
* [x] show type in brackets after blend name

**Comment by danhorho** [comment]
There is not **sort_order** column in **core_blend** table.  
**type** column has no data.

**Comment by melish** [comment]
> There is not **sort_order** column in **core_blend** table.
> **type** column has no data.

There is now (in fixtures), it's just that I haven't yet loaded them on ozone.edw.ro
