### ISSUE TITLE
Controlled substances (Lookup tables)

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#251]
Following the ticket  #210 the specifications for controlled substances form are:

Table columns: 
* Annex
* Group
* Name
* ODP
* Formula
* Number of Isomers
* MinODP
* MaxODP

Please remove:
1. table caption
1. Index column
1. Sort default
1. Clear button

Control 
<img width="422" alt="screenshot 2018-12-11 at 16 31 13" src="https://user-images.githubusercontent.com/533311/49807219-30abfc00-fd62-11e8-8fbd-95b7cb719439.png">
must be migrated in three separate controls (**drop-down controls in sync**): Annex, Group, Name.

## backend specification

API: /api/group-substances/
* Annex: first digit from group_id
* Group: group_id
* Name: name
*  ODP, Formula, Number of Isomers, MinODP, MaxODP: will be added in the API
* user sort_order from the API for sorting

**Comment by danmisailescu** [comment]
replace search ODP with search Formula
