### ISSUE TITLE
Prerequisites for HAT reporting (data forms 7 and 8)

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#259]
Q: What kind of evidence do you have that a party has expressed its  intention to use the high-ambient temperature exemption? Is there (or rather, should there be) something in the database, in a manner similar to the Essential nomination and exemptions?

A: The Parties is required to have notified the Secretariat at least one year before the freeze data (paragraph 29 of decision XXVIII/2 – see https://ozone.unep.org/node/94313).  Therefore we can have a table/data entry screen for Secretariat to record such notifications

**Comment by danhorho** [comment]
We can try to use **ExemptionNomination** form.

**Comment by melish** [comment]
The is_high_ambient_temperature flag for each party is enough as a prerequisite condition. No need to record in the database any other intention to use the HAT.
