### ISSUE TITLE
Additional submission fields to be sent by the web forms

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#261]
These fields should be sent from data form to API when creating a new submission:

- Submission.filled_by_secretariat (depending on the current user/role)
- SubmissionMethod ('Web form')

**Comment by sorinstelian** [comment]
I think the `filled_by_secretariat` field can be inferred in the backend, as we have the request.user available.

**Comment by mihai-macaneata** [comment]
Everything works as described
