### ISSUE TITLE
Management command to migrate existing Art. 7 reports

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#267]
Use the legacy_submissions.xlsx data file (found in Business Data Model folder) to initially migrate worksheet "Overall" into the Submission table.

Field mapping for Submission model: (Excel columns are listed in square brackets):

cloned_from_id: NULL
country: name of country linked via party_id [CntryID]
created_at: [DateCreate]
created_by_id: NULL or admin user id
current_state: 'finalized'
date: [DateReported]
designation: ''
email: ''
fax: ''
filled_by_secretariat: False
flag_provisional: False
flag_superseded: False
flag_valid: True
last_edited_by_id: NULL or admin user id
obligation_id: 1
organization: ''
party_id: id of country designated by [CntryID] (look by Party.abbr)
phone: ''
postal_code: ''
previous_state: NULL
remarks_party: [Remark]
remarks_secretariat: [SubmissionType]
reporting_officer: ''
reporting_period_id: lookup ReportingPeriod.id via [PeriodID]
schema_version: 'legacy'
submitted_via: 'Legacy' (add this value to model SubmissionMethods)
updated_at: [DateUpdate]
version: 1
workflow_class: 'default'

Field mapping for Article7Questionnaire model:
submission: fk to Submission id
has_imports: [Imported]
has_exports: [Exported]
has_produced: [Produced]
has_destroyed: [Destroyed]
has_nonparty: [NonPartyTrade]
has_emissions: False
remarks_party: NULL (TBD for myself - these fields are not visible in the UI)
remarks_os: NULL

~Field mapping for Article7Flags~: **Moved to #306**
- This is not a 1:1 mapping. Each flag generates a new row in Article7Flags
- Only incomplete currently seems to be implemented in models . Possibly related to #160
- AI_ComplRep, AII_ComplRep, ... F_ComplRep are the equivalent of not(flag_incomplete) for the corresponding annex group (Article7Flags.annex_id, group_id)
- In the legacy system there was only one group in Annex F. Map that field to the current F-I group, although it's not entirely right

- TBD for [Checked_Blanks], [Blanks], [Confirm_Blanks]. To check with @sorinstelian about how/where to migrate these flags

These fields in the Excel file can be safely ignored:
DataID, UserCreate, UserUpdate, TS

**Comment by alexkiro** [comment]
> Field mapping for Article7Flags:

FWIW, we'll skip these for now, and them to the import management command after we clarify more details about them.
