### ISSUE TITLE
Latest submissions

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#275]
Latest submission -> All submissions
Per page should go at the bottom on the right side.
Remove "Type to search"
Remove all "Clear" buttons, replace them with only one "Reset filters" link.
Search input should be half of the existing size.
Filter by Party should be half 75% of the existing size.
We have different drop-down controls on the same page.
Period from: -> Period from, size should be 30% of the existing size.
Period to: -> Period to, size should be 30% of the existing size.
All filters should be on the same row.

All table elements should have the texts aligned to left. Numeric values like period year, version are aligned to the center, and numeric data is aligned to right.

Remove "Clone", "Submit", "Delete". The user must see the details in order to perform these operations.

**Comment by mihai-macaneata** [comment]
> Remove "Clone", "Submit", "Delete". The user must see the details in order to perform these operations.

@melish will talk to @nico4  about these changes.
Everything else is done
