### ISSUE TITLE
data form 1 - modals

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#289]
Following #288 , the table rows can be edited using modal forms.

Question: **Should users change the substance name and country from this form?**

<img width="915" alt="screenshot 2018-12-12 at 14 33 01" src="https://user-images.githubusercontent.com/533311/49870054-e6d31c80-fe1a-11e8-8795-f29e2d2f808a.png">

Page title:  Edit "HALON-1211" substance. 
Description text: **All the quantity values should be expressed in metric tonnes ( not ODP tonnes).** 
The values are saved in the table, as you type. Close the form using the button below.

All labels should have font-weight: normal.
Avoid capital case in labels (e.g. Total Quantity Imported for All Uses (new)).  Avoid ":" in label values.
All numeric input controls should have 20% of their current size.
Decision controls should be larger.

Avoid separation lines.

**Comment by mihai-macaneata** [comment]
> Question: Should users change the substance name and country from this form?

Yes

**Comment by nico4** [comment]
Avoid capital case in labels (e.g. Total Quantity Imported for All Uses (new)). Avoid ":" in label values.

**Comment by nico4** [comment]
Description should go after the heading
