### ISSUE TITLE
Data form - Questionnaire fails to save

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#290]
There is a strange error on trying to save the webform.

<img width="1307" alt="screenshot 2018-12-12 at 14 43 27" src="https://user-images.githubusercontent.com/533311/49870629-a2e11700-fe1c-11e8-9b2a-a69be63a6c09.png">

These are the values on imports.

<img width="1697" alt="screenshot 2018-12-12 at 14 46 25" src="https://user-images.githubusercontent.com/533311/49870667-bab89b00-fe1c-11e8-997c-a13ec614caf3.png">

**Comment by mihai-macaneata** [comment]
Will be solved by #282
