### ISSUE TITLE
User roles test cases

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#298]
Available roles:

- Ozone Secretariat
  - Ozone Secretariat Edit (OS.SE) - can enter data on behalf of a Party (e.g. can create Submissions)
  - Ozone Secretariat Read-Only(OS.SRO) - can view all data reported by any Party, but can't make changes.
- Administrator (OS.A) - view change log for any submission
- Party:
  - Party Reporter (PARTY.PR) - can create Submissons, can view all data reported by his Party. Each Party Reporter is assigned to a single Party. There can be one or more Party Reporters for one Party.
  - Party Read-Only (PARTY.PRO) - It's similar to the Secretariat Read-Only role, but restricted to a single Party.
- Public User (PU) - won't have direct access to any part of the reporting system

Test cases:

1. As OS.SE I can create Submissions on behalf of a Party.
1. As OS.SE I can edit/delete Submissions on behalf of a Party.
1. As OS.SE I can access admin area.
1. As OS.SRO I cannot create/edit/delete Submissions.
1. As OS.SRO I cannot create/edit/delete blends.
1. As OS.SE I can access admin area in read-only mode.
1. As PARTY.PR I can view only data reported by my Party.
1. As PARTY.PR I can only edit/delete Submissions on behalf of my Party.
1. As PARTY.PR I cannot access admin area.
1. PARTY.PRO I can view only data reported by my Party.
1. As PARTY.PR I cannot access admin area.
1. As PARTY.PRO I cannot edit/delete Submissions on behalf of my Party.
1. As PARTY.PRO I cannot create/edit/delete blends on behalf of my Party.
1. As PARTY.PRO I cannot access admin area.
1. As PU I cannot view any Submissions.
1. As PU I cannot create/edit/delete any Submissions.
1. As PU I cannot create/edit/delete any blends.
1. As PU I cannot access admin area.

**Comment by sorinstelian** [comment]
1. Only administrator can view change log?
2. Administrators can create submissions?
