### ISSUE TITLE
After redeployment, auth_token is not valid and dashboard is empty because of unauthorized

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#302]
i.e. after redeployment = after clearing the database
we should find a way to force login when auth_token / cookies are not valid

**Comment by sorinstelian** [comment]
Assigning to @mihai-macaneata as the frontend simply needs to request another token when getting Unauthorized.

**Comment by mihai-macaneata** [comment]
Fixed in a3f4e11161d953f67307727572a2cc6e636c04cb  dff1c2bb5f80abf8eabf6217acd610054606f6f5
