### ISSUE TITLE
i18n & l10n

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#303]
### Backend

 - [x] Configure django translation and load translations
 - [x] Mark strings for translation, these should only be the error messages _(AFAICT, these are already done)_
 - [x] If translations are not available, either at all OR for a specific key, fallback to English

### Frontend

 - [x] Integrate a VueJs plugin for translation ([vue-gettext](https://www.npmjs.com/package/vue-gettext) looks promising)
 - [ ] Async load translations from server (ideally on a per-language basis)
 - [x] Mark strings for translation
 - [x] Add drop-down with available languages
 - [ ] Add extra `Accept-Language` header to all APIs according to the selected language
 - [ ] Store cookie with the last selected language, to be used for new sessions
 - [x] If translations are not available, either at all OR for a specific key, fallback to English

### Deployment

 - [x] Command line tool that updates translation strings
    - [x] Extract translatable strings from the backend, using django-admin tool
    - [x] Extract translatable strings from the frontend, using a third-party tool ([vue-gettext](https://www.npmjs.com/package/vue-gettext) looks promising)
 - [x] Command line tool to compile translations
    - [x] Compile backend translations, using django-admin tool
    - [x] Compile frontend translations, from po to json
    - [x] Serve frontend translations, publicly
 - [x] Add a Weblate server
 - [x] Integrate Weblate server into a Git Repository
 - [x] Figure out authentication for Weblate server.
 - [x] Automatically update the pot file after commit
 - [x] Modify staging deployment to include translation files (if it doesn't already)
 
### To be determined/clarified

 - [X] Who translates the app? Do we need to provide a translation app such as [pootle](https://pootle.translatehouse.org/)
   - The application is translated by the user via the Pootle interface
 - [x] Depending on the above, determine where to store to the translations: same repo/another repo/third-party
 - [X] Automate translation string generation on new commits (can be done with Jenkins or similar tools). Nice to have.
   - Yes

### Backend

 - [x] Return datetime values in the Nairobi timezone _(should already be the case)_
 - [x] Return all datetime values in the same format _(should already be the case)_

### Frontend

 - [x] Display the datetime in the user's locale (e.g. using [momentjs](https://momentjs.com/)).
 - [ ] No timezone processing is required ATM. We will display the date in the timezone received from the server.

### To be determined/clarified

 - [X] Should the user be able to change the datetime format in their user settings?
   - Not at this time

**Comment by alexkiro** [comment]
Backend and deployment side should be finished now. For the frontend translations those are put in `frontend/public/` and therefore included in the build process.

 - `http://localhost:8080/translations.json` while running in development mode
 - `https://HOST/translations.json` in staging/production

**Comment by alexkiro** [comment]
> * Async load translations from server (ideally on a per-language basis)

@danmisailescu if we can do this on a per-language basis from the frontend. i.e. we somehow don't load all translations, but only the language that we currently want to display let me know. And I'll change the compile method to create separate JSON files for each language.

**Comment by alexkiro** [comment]
> And I'll change the compile method to create separate JSON files for each language.

FWIW, these was done afterall. JSON translation files are now generated in separate files for each language, in `frontend/public/translations/<language-code>.json`
