### ISSUE TITLE
Date of submission 

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#321]
To consider: we might need an explicit field or property for the date of submission (the moment - Nairobi time - when the submission was submitted).
This value would also be shown in the user interface (read-only)

**Comment by sorinstelian** [comment]
Indeed, we should add this field; it would be a good way of knowing when a submission was actually submitted (other possibilities available, but not ideal).

**Comment by danhorho** [comment]
See **public.core_submissioninfo.data** column.

**Comment by melish** [comment]
It is not about the core_submissioninfo.date field.
This new field represents the moment when "Submit" action was performed (it's related to the workflow and not directly editable by users.
IMO it should be a field on the "Submission" model.

**Comment by danhorho** [comment]
**Proposal**
To add a new table: SubmissionStateHistory:

- id
- submission_id
- state
- date

where "state"  values are possible states for a submission.

**Comment by danhorho** [comment]
**Proposal Update**
To add a new table: SubmissionStateHistory:

- id
- submission_id
- state
- enter_date
- exit_date

where "state" values are possible states for a submission.

**Comment by melish** [comment]
>  To add a new table: SubmissionStateHistory.
Not necessary. There is already core_historicalsubmission (automatically created by the framework) serving the same purpose, but having a slightly different structure.

**Comment by sorinstelian** [comment]
@danmisailescu : addded `submitted_at` field in submissions list and submission detail.

**Comment by danmisailescu** [comment]
@melish @sorinstelian  Done:
![Untitled.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c0fcbafc51ee00011888144/125516c66e82c728ace21e0d46dd9a8e2a968fac8babf301b44fff9e2c4533317346f6282083ba2eb9447f04565b4bf941595c10fbacdf7fa0e32e6c981e5ab38532022d8c6853beb2901eb80bbb258f4980b4bc894fc4ee3e2df5c6.png)

**Comment by sorinstelian** [comment]
@nico4 @danmisailescu  : The field does not seem to be displayed at all even for "submitted"/"finalized" submissions. The API does however return non-null values in such cases. Does the UI need it in a different format than the current one (right now it looks like `2019-01-11T19:16:34.232191+03:00`)?

**Comment by sorinstelian** [comment]
The issue described in the above comment seems to have been fixed.
