### ISSUE TITLE
Remove Unspecified and Czechoslovakia from fixtures

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#322]
These two parties should be removed, but addressing the implications:
- [x] the pk's of remaining parties will probably have to change
- [x] existing initial/test data (fixtures, submissions, etc.) should be smoothly migrated
- [x] legacy data imported in #318 and #313 will have to be executed again to double-check if there is anything related to these two invalid countries

**Comment by alexkiro** [comment]
> * legacy data imported in #318 and #313 will have to be executed again to double-check if there is anything related to these two invalid countries

Nothing related to these two.
