### ISSUE TITLE
Submission type

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#323]
We need a lookup table for the types of submission. By type I mean "reporting channel" (web, email, fax, letter etc.). There are currently (in source code) only WEB, API and Legacy types, but while checking the existing data (table Overall, column SubmissionType) I realized there may be more granular values.

This new field may be added to the user interface (only for OzSec to choose from)

**Comment by danhorho** [comment]
This column looks more  like  the Remark column.
For example, 4443 of 5623 records this column has "This period was before system for checking zeros/blank cells." value.
Anyway, "reporting channel" is a better name.
Q: It is possible  to have a submission submitted using many reporting channels?

**Comment by danhorho** [comment]
See **public.core_submission.submitted_via** column.

**Comment by melish** [comment]
Add a new dropdown in submission info tab: "Submission method" with options from model SubmissionMethods (via API or duplicated in frontend code - at your choice). Currently the numeration contains 'Web form', 'Email' and 'Legacy'. Please add two new values: 'Paper' and 'API'.

The default value when creating a new submission is 'Web form' (disabled for parties, enabled for secretariat). When cloning a submission, the previous value should be kept (but still allow changing by OzSec. i.e. different versions could use different submission methods).

**Comment by catalinjitea** [comment]
@mihai-macaneata backend part is done.

**Comment by mihai-macaneata** [comment]
@catalinjitea there might be a bug that prevents me from creating submissions related to this.
I'm getting this error https://i.gyazo.com/104c94a770ba1beba54d533f7a8f9bc7.png when creating a submission in dashboard, preventing me to create submissions

**Comment by sorinstelian** [comment]
@mihai-macaneata : did you try on staging? things seemed to work quite ok there.
