### ISSUE TITLE
Make application work on HTTPS

### ISSUE THREAD

**Issue by alexkiro** [eaudeweb/ozone#344]
The application is currently not working on HTTPS, we need to investigate why that is the case and fix the issue. 

 - [x] Ensure application backend/frontend works on HTTPS
 - [x] Configure staging deployment on HTTPS

---- 

Note, it appears that the Hyperlinked fields in the API isn't aware of the protocol used.

**Comment by sorinstelian** [comment]
Related to: https://github.com/eaudeweb/ozone/issues/209

Also see: https://stackoverflow.com/questions/22279893/djangorestframework-https-links-with-routers-and-viewsets
