### ISSUE TITLE
data form 7 - instructions

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#347]
h1. Instructions on data on consumption (imports) under the exemption for high-ambient-temperature parties (data form 7)

If your country formally notified the Secretariat, as specified under paragraph 29 of decision XXVIII/2, of its intention to use the exemption for high-ambient-temperature parties and is listed in Appendix II of decision XXVIII/2, please use data form 7 to report quantities of new HFCs imported for use in approved subsectors as listed in appendix I to the decision. Those imports must be for use within your country and not for export. In case other subsectors are approved after the assessments under paragraphs 32 and 33 of decision XXVIII/2, please use the additional columns in the data form to specify the approved subsectors and the amounts imported for use in those subsectors. Only bulk gases for servicing of equipment in the exempted subsectors should be reported here, not gases imported inside pre-charged equipment.

**Comment by danmisailescu** [comment]
refactoring getInstructions + directory structure
