### ISSUE TITLE
Add substances vs annex group filter

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#353]
When adding substances:
Choose one annex group > Choose one substance > Remove the annex group => something remains in the substance select, but the control cannot be used anymore, even if adding some other annex group (different than the initial one).

Expected behaviour: 
option 1) Show all substances when no annex group is selected
option 2) When an annex group is removed, corresponding substances (belonging to the same group) not yet added in the table should be removed also

Also note an inconsistency: after adding one or more substances, the Annex select is emptied, but the filtering remains active (only substances from the previously selected annex groups are shown in the substance dropdown, even though the annex dropdown is empty). This would be fixed automaticall in case we go for option 1) above.

**Comment by mihai-macaneata** [comment]
The chosen behavior  was 1) . In addition to that, the selected substances reset when adding or removing a group in the group filter
