### ISSUE TITLE
Don't disable tabs for "No" answers in the questionnaire

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#354]
i.e. Leave the corresponding tab enabled even when users chooses "No" as an answer to the corresponding question in the questionnaire.
However, keep the tab disabled until users chooses either Yes or No to the corresponding question

**Comment by nico4** [comment]
@melish Should the "disabled" tabs content be read-only?

**Comment by melish** [comment]
No, read-write + special validations when the flag is FALSE.
Parties must be able to enter comments (tab-level field), sometimes to add rows (with zero total quantity) and remarks (row-level remarks).

**Comment by nico4** [comment]
@melish Questionnaire fields are still mandatory? Party should respond to all the questions before saving?

**Comment by melish** [comment]
Yes

**Comment by melish** [comment]
Further clarifications/consolidation:
- [ ] Until either Yes or No is selected in the questionnaire, the corresponding tab is disabled
- [ ] When No is selected, users won't be able to add rows in any table from the corresponding tab (don't show Substance/Blend/Validations sidebar). They will still be able to enter Comments in that tab
- [ ] When Yes is selected, rows are added, then No is selected, all previously added rows will be removed
