### ISSUE TITLE
Order of quantity fields in modal edit

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#367]
This is about the vertical order of fields in the additional edit screen (quantities and decision by component):

* [x] Move QPS right after Feedstock
* [x] Move Laboratory and analytical before Process Agents
* [x] Move Polyols after Other

* [x] Ideally keep labels on a single row

**Comment by mihai-macaneata** [comment]
> Move QPS after Feedstock

It's already after feedstock everywhere. If not, can you show me where ?

**Comment by mihai-macaneata** [comment]
closed in cb8a32cb6a66250235ee00ac79a8f69defbd57a0
