### ISSUE TITLE
Small changes in Production > Annex F2

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#373]
![image](https://user-images.githubusercontent.com/1218168/50300175-4620d480-048c-11e9-99e3-91b6688b32e7.png)

* [x] It's not correct to group (4b) captured for destruction together with feedstock (they are unrelated) and separately from (3). Remove the "Production for feedstock uses within your country" heading completely and move "Production for exempted essential, critical or other uses within your country" one the next line (above columns 5+6), if possible
* [x] column (7) production for Article 5 countries does not apply to Annex F substances, remove it from the special table for HFC-23

* [x] always show FII substances last and grouped under the same sub-table. Mixing different layouts is really confusing:

![image](https://user-images.githubusercontent.com/1218168/50300474-39e94700-048d-11e9-8253-302b86174161.png)

* [x] columns (3), (4a), (4b) should have the info icon + tooltips

* [x] find a way align columns for FII substances vs rest of annex groups (columns 4a+4b vs 4, 5+6 vs the other 5+6 respectively, etc.)

* [x] special validation rules for production tab
a. Column (3) should not be empty (total production for all uses / captured for all uses for FII)
b. For annexes A-C, total production (3) should be >= (4) + (5) + (7)
c. For annex E, total production (3) should be >= (4) + (5) + QPS
d. For annex F1, total production (3) should be >= (4) + (5) - in fact same as rule b. but there is no (7) for annex F
e. For Annex F2, captured for all uses (3) should be >= (4a) + (4b) + (5)

**Comment by mihai-macaneata** [comment]
closed in #383
