### ISSUE TITLE
Shorter database table names

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#375]
* To be analysed: what is the impact of using shorter table names (only in the physical database), e.g. instead of reporting_article_seven_non_party_trade to have reporting_a7_non_party_trade
Mainly concerning reporting_* tables.

* why HAT tables have a different naming convention (e.g. core_highambienttemperatureimport?) Shouldn't it be reporting_hat_import?

**Comment by sorinstelian** [comment]
- Using shorter table names should not cause any issues
- HAT tables should indeed have different names
