### ISSUE TITLE
Analyze behavior of filled_by_secretariat when cloning and importing legacy data

### ISSUE THREAD

**Issue by sorinstelian** [eaudeweb/ozone#386]

**Comment by sorinstelian** [comment]
@melish:

Right now, `filled_by_secretariat` is actually a property on the `Submission` model that takes into account the `created_by` field (which references a user).

I would suggest that when cloning a submission, created_by is set to the the user performing the cloning. Also, when importing legacy data, a secretariat user should probably be used.

**Comment by melish** [comment]
Given that `filled_by_secretariat` is a flag used to enable certain actions (like fast-track processing) or fields (like the party comments), it makes sense to replace `created_by` with the actual user creating the new version (which includes cloning). 
Not sure though if it's worth keeping the original creator in another field - let's add it later only if useful.

When importing legacy data we are using username `admin`, which will have the `is_secretariat` flag set.

**Comment by sorinstelian** [comment]
Solved in b3005fc1310afa0a1e0711fc18c95fb4090a0d75
