### ISSUE TITLE
Login redirect

### ISSUE THREAD

**Issue by mihai-macaneata** [eaudeweb/ozone#406]
Login redirects to :8000/api on localhost. 
Trying to access any route on :8080 redirects to :8000/admin 

In development mode the vue app is served by a webpack server that runs on a different port than the django server, therefore login should redirect to :webpack_port/reporting/dashboard

Not sure if it's worth trying to make django aware of the port that webpack is using in order to avoid hardcoding the 8080 port

**Comment by mihai-macaneata** [comment]
Please test if you can replicate the bug before working on it

**Comment by alexkiro** [comment]
> Please test if you can replicate the bug before working on it

It definitely replicates, I left a small [note](https://github.com/eaudeweb/ozone/blob/develop/ozone/core/admin.py#L122) about this in the code, that it won't work on development. :smile: 

> Trying to access any route on :8080 redirects to :8000/admin

@mihai-macaneata this is true, but it's supposed to also add the `?next=` query parameter, so the correct redirect on the correct port would be used after a successful login. Is this broken?

**Comment by mihai-macaneata** [comment]
Running pip install requirements solved the problem
