### ISSUE TITLE
RO secretariat and party can edit submissions on staging

### ISSUE THREAD

**Issue by mihai-macaneata** [eaudeweb/ozone#421]

**Comment by sorinstelian** [comment]
Steps to reproduce? :)

**Comment by mihai-macaneata** [comment]
The bug was happening because the feature was no implemented. The permissions implemented atm in art7, except for comments and flags are referring only to the state of the submission, not the current user.

**Comment by mihai-macaneata** [comment]
This also needs to solve #429
