### ISSUE TITLE
Reporting channel should only be editable for secretariat users

### ISSUE THREAD

**Issue by sorinstelian** [eaudeweb/ozone#429]
But only if the Submission has been created by OS.

Also, even if in the interface it should remain in the Submission Info tab, in the backend it should be moved in the Submission model

**Comment by mihai-macaneata** [comment]
This will be solved by #421

**Comment by sorinstelian** [comment]
Frontend part of this will be solved by #421, backend will need its own code.

**Comment by catalinjitea** [comment]
@sorinstelian can we close this issue?

**Comment by sorinstelian** [comment]
@catalinjitea Not until #429 is solved, I guess.

**Comment by sorinstelian** [comment]
Closing, as #421 has been closed.
