### ISSUE TITLE
Remarks fields on each data entry from a submission should be editable after submit

### ISSUE THREAD

**Issue by sorinstelian** [eaudeweb/ozone#447]
Right now they behave the same as any data field (i.e. not editable by anyone).

Permissions should be the same as for the general remarks field on the Submission model.
See https://github.com/eaudeweb/ozone/issues/374

**Comment by sorinstelian** [comment]
While we're at it, we should also return, on the submission endpoint, two flags (e.g. can_change_remarks_party, can_change_remarks_secretariat) that will signal whether the current user can change these flags on the current submission and on each data entry.

There is no need to return other flags since the logic for general (per submission remarks) and per-data entry remarks is the same.

**Comment by catalinjitea** [comment]
Closed in #456
