### ISSUE TITLE
Missing decision_polyols from api

### ISSUE THREAD

**Issue by irina-botez** [eaudeweb/ozone#448]
In the _article7-exports_ list, there is no entry for _decision_polyols_ even though _quantity_polyols_ exists.

**Comment by sorinstelian** [comment]
After also consulting with @melish , we do not believe that the field should exist, there are probably no decisions required for polyols import/export.

Will close for now as it is not a bug (a decision_polyols field was never required in the specs).

If the user will want to add additional comments about polyols imports/exports, he/she can use the remarks field.
