### ISSUE TITLE
The submission list should include a clone button 

### ISSUE THREAD

**Issue by mihai-macaneata** [eaudeweb/ozone#45]
The clone button calls the API clone method and creates a new submission that has a new version and its state will be data entry

**Comment by mihai-macaneata** [comment]
Frontend part is implemented, but the feature does not work at the moment, because current period is defined in backend as the current year.

**Comment by catalinjitea** [comment]
#143 is implemented and closed. I think we can close this issue.

**Comment by sorinstelian** [comment]
@mihai-macaneata : can we close this?
