### ISSUE TITLE
Destruction section: data binds to the wrong field when adding/editing an entry

### ISSUE THREAD

**Issue by irina-botez** [eaudeweb/ozone#450]
The contents of the field _Remarks (Secretariat)_ appear under the _Remarks (Party)_ column.

Same goes for the api: the data entered in the Remarks (Secretariat) field is binded to the _remarks_party_ key in the _article7-destructions_ list.

**Comment by mihai-macaneata** [comment]
The bug wasn't the one I was  trying to reproduce. The problem was that the labels for remarks_os and remarks_party were inversed in destruction, nonparty and emissions
