### ISSUE TITLE
Other obligations 

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#451]
All other obligations should be displayed instead of "Other" row from "Obligation" drop-down control. The main obligations "Article 7", "Essential" and "HAT" should be displayed first.

https://cl.ly/1aec1a4feeaf

The entire list is on ticket https://github.com/eaudeweb/ozone/issues/227#issuecomment-452731306.

**Comment by catalinjitea** [comment]
@mihai-macaneata backend part is done and pushed into `develop`.
As we discussed you need to update form generation logic to use form_type `other` instead of `letter` when an obligation has flag `other=True`.
