### ISSUE TITLE
Cleanup i18n messages

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#486]
Remove unused i18n message like "twitter".

**Comment by danmisailescu** [comment]
@nico4 That text exists in the page Register.vue that is referenced via path /pages/register.

I've walked through all the application files and replaced all existing strings in the markup and javascript code with references to translations. 

At this moment I don't know what is "unused" or not.

I think @mihai-macaneata knows what I sections can be deleted fom the application.
