### ISSUE TITLE
Comments on submission attachments 

### ISSUE THREAD

**Issue by alexkiro** [eaudeweb/ozone#497]
Should attachments have general comments for party and secretariat as all other form tabs currently have? 

Refs. #418

**Comment by sorinstelian** [comment]
As discussed with @melish, there should be a "description" field for each file, so uploader can state the purpose/content of the file.

**Comment by catalinjitea** [comment]
Backend has already support for adding a "description" for an uploaded file. We just need to make it visible in the interface.
@mihai-macaneata

**Comment by nico4** [comment]
Vreau un buton de upload. Serios. Asa cum este acum, este absurd.
