### ISSUE TITLE
Saving /api/submissions/pk/submission-info fails on staging 

### ISSUE THREAD

**Issue by mihai-macaneata** [eaudeweb/ozone#517]
User: party
with error : __all__: ["Unexpected Error!"]
Can't reproduce the bug locally. 
Maybe someone check the django logs on staging ?

**Comment by sorinstelian** [comment]
I will take a look after merging the refactored permissions code on staging.

**Comment by sorinstelian** [comment]
Failure is due to reporting channel info being lost for all existing submissions on staging; this happened when it has been moved from SubmissionInfo to Submission. Assigning to @catalinjitea for a quick fix.
