### ISSUE TITLE
Create submission improvements

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#520]
https://cl.ly/38461197d37c

1. Make "Create submission" box larger to fit all values inside the "Obligation" drop-down.
2. Remove vertical scroll from "Obligation" drop-down

**Comment by mihai-macaneata** [comment]
1. Solved
2. Will not remove the vertical scrollbar since with the current data, it's already the size of a laptop screen without scrollbar. If more obligations appear, the layout will break
