### ISSUE TITLE
HAT fixes

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#521]
- [x]  "Submission Info", As a Party when I create a new submission, the default value for "Reporting channel" is "Web form".
- [x] As a Party I cannot save the submission. The error is "Unexpected error".
- [x] Blend name should be displayed on a single row. https://cl.ly/522134484ae0 
- [x] Attachments  are not working.

**Comment by mihai-macaneata** [comment]
As a Party I cannot save the submission. The error is "Unexpected error".
 There is already another ticket for this #517
