### ISSUE TITLE
Frontend translation tests fail

### ISSUE THREAD

**Issue by mihai-macaneata** [eaudeweb/ozone#525]
https://travis-ci.org/eaudeweb/ozone/jobs/482799818

**Comment by alexkiro** [comment]
Just a race condition, somebody was editing the translation while Travis was extracting the new text and updating it. 

```

1.30s$ git pull
From https://github.com/eaudeweb/ozone-translations
   a03eea5..51070f2  master     -> origin/master
error: Your local changes to the following files would be overwritten by merge:
	frontend/locale/ru/LC_MESSAGES/app.po
Please commit your changes or stash them before you merge.
Aborting
Updating a03eea5..51070f2
The command "git pull" exited with 1.
```

I don't think it's worth doing something complex here, as it works on the next run of the build, and such scenarios will disappear when changes to the strings won't happen as often as they are now.
