### ISSUE TITLE
Users with `is_superuser` should have special privileges

### ISSUE THREAD

**Issue by sorinstelian** [eaudeweb/ozone#551]
A user with is_superuser will be able to do in the API things that secretariat cannot do, including editing party-creating submissions or editing submissions that are not in "data entry'.

**Comment by melish** [comment]
see also #7

**Comment by sorinstelian** [comment]
Administrators (OS.A, i.e. superuser accounts) should be able to delete any submission in data entry, even if they were created by parties.

TBD: OS.A are the same as superusers?

**Comment by melish** [comment]
Yes, let's consider OS.A superusers

**Comment by sorinstelian** [comment]
We will make sure that Submissions are available in the admin interface for changing flags and states.

**Comment by sorinstelian** [comment]
SubmissionInfo should also be available there.

**Comment by nico4** [comment]
I cannot delete from one click a submission from Django Admin.

**Comment by melish** [comment]
I suggest a custom override of "Delete selected submissions" action in Django admin.

**Comment by nico4** [comment]
Not working. https://www.loom.com/share/b8771baa31784f22b63966bb30c90dd3

**Comment by nico4** [comment]
My mistake, it should work only from the Django Admin interface.
