### ISSUE TITLE
How will the is_staff flag be taken into account?

### ISSUE THREAD

**Issue by sorinstelian** [eaudeweb/ozone#552]
We could make a user with `is_staff` behave similarly to a user with `is_secretariat` in regards to API rights, while is_staff would also grant access to the admin interface.

However, is there a need for secretariat-edit users that cannot access the admin interface?

**Comment by sorinstelian** [comment]
@nico4 : is there a need to have some secretariat-edit users that cannot access the admin interface?

**Comment by sorinstelian** [comment]
As part of the solution for #551 , the Submission and SubmissionInfo models are now editable via admin interface.

**Comment by melish** [comment]
Not necessary. There is also the superadmin(supervisor), see #551
