### ISSUE TITLE
user profile message error

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#562]
https://cl.ly/b1b0da64d0df

**Comment by nico4** [comment]
in plus, la reload https://ozone-staging.edw.ro/reporting/user-profile pagina nu incarca datele din backend.

**Comment by sorinstelian** [comment]
> https://cl.ly/b1b0da64d0df

@catalinjitea is working on solving this

**Comment by sorinstelian** [comment]
Solved in https://github.com/eaudeweb/ozone/pull/559
