### ISSUE TITLE
Behavior of cloning, versions and superseded flag for non-article 7 submissions

### ISSUE THREAD

**Issue by sorinstelian** [eaudeweb/ozone#574]
It looks like cloning, version and superseded should be restricted to data reporting submissions.

**Comment by sorinstelian** [comment]
We will do this first for Nominations, where versions do not make sense. In the mean time we can decide what other obligations should not have versions.

**Comment by sorinstelian** [comment]
Implemented for Exemption.

Based on feedback for this, will proceed with applying it for other obligations too.

**Comment by melish** [comment]
Only Art7, RAF and HAT should have versions.
Letters, Transfers, EUN/CUN, Process Agents and other obligations don't need versions.

**Comment by melish** [comment]
I suppose FormTypes.Transfer, ProcAgent and Other should be added to NOT_CLONEABLE and is_versionable()

**Comment by sorinstelian** [comment]
@melish : Right now we keep a version field internally for all types of submissions, which may be actually useful even for non-versionable ones. However, in the case of those, we do not supersede anything. :)
I think we should have a `has_versions` field on the Obligation model, this way it will be easier for the UI to choose whether to display the version field in the dashboard (right now it is always displayed).

**Comment by sorinstelian** [comment]
@melish : do you think my above suggestion is needed or should we just close this issue?

**Comment by melish** [comment]
I think it would be useful, please add it.

**Comment by sorinstelian** [comment]
Backed part implemented in #574.

I think we should also make the UI not display the "version" field in the dashboard for obligations that do not support submisison versioning.

**Comment by sorinstelian** [comment]
@mihai-macaneata : Also added a `is_versionable` flag on Submission to make things easier in frontend.
