### ISSUE TITLE
RAF - are blanks-related flags needed here?

### ISSUE THREAD

**Issue by sorinstelian** [eaudeweb/ozone#579]
They have been added for now to the SubmissionFlagsSerializer.

**Comment by melish** [comment]
Blanks are not needed for RAF forms

**Comment by sorinstelian** [comment]
Solved in https://github.com/eaudeweb/ozone/pull/634

**Comment by sorinstelian** [comment]
The flags are greyed out in the RAF forms... not sure whether they should be there at all.

@nico4 @melish : what do you think?
