### ISSUE TITLE
"Create submission" default values

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#584]
We think it would be nice for the “Create submission” area to have default values for “Obligation” and “Period”. These should be “Article 7” and “the immediate year preceding the current year” (2018 for this year). This way, the very initial view has some utility.

The default values should be set from the Django Admin.

**Comment by nico4** [comment]
In fact, the same 2 default values would be useful for the other two areas – namely the sections on “Data entry submissions” and “All submissions”.

**Comment by sorinstelian** [comment]
@nico4 : How do we configure it from the Django admin: "the immediate year preceding the current year"? What are the other options? :) Also, is this really useful? :)

**Comment by melish** [comment]
@sorinstelian @mihai-macaneata 
Use a default selection the most recent period having is_reporting_open = true as

**Comment by sorinstelian** [comment]
Will implement a `default-values/` endpoint to return this information - values returned can also be null, which would mean there is no default.

**Comment by sorinstelian** [comment]
`/api/default-values` endpoint added in #644 . Default obligation is now configurable via the `is_default` flag on the Obligation model.

**Comment by melish** [comment]
Front-end part still to be implemented

**Comment by nico4** [comment]
Front-end part still to be implemented
