### ISSUE TITLE
Submission info mandatory fields

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#586]
Indicate which fields are mandatory and which ones are not (maybe using *).  I suggest the following fields be mandatory:

* Name of the reporting officer
* Postal address  OR   E-mail
* Country (automatically prefilled with the party of the new submission)

**Comment by nico4** [comment]
@melish what should we do then with the historical data which does not have these fileds completed?

**Comment by melish** [comment]
If the fields are mandatory only in the user interface, when cloning and changing a legacy submission, they will have to enter some values. It's the same principle as for validations failing with historical data.
