### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#587]
Date format – display using dd mmmm yyyy (where month is the text January/February/…../December).  This can be a general approach for all date fields to avoid creating confusing between mm/dd/yyyy and dd/mm/yyyy.  Where the display field for the date is short, the short form of the months can be used (Jan/Feb/…/Dec).

**Comment by mihai-macaneata** [comment]
I think the date structure in backend should remain the same and I'll change the way it is displayed.
Is it ok ? @sorinstelian @melish

**Comment by nico4** [comment]
The ISO format sent and received to/from server.

**Comment by melish** [comment]
@nico4 I don't get your last comment
@mihai-macaneata Yes, the date in the backend (i.e. in the API) should remain the same and you only apply formatting in the user interface.

**Comment by danmisailescu** [comment]
Yes, we are doing this now. @melish @nico4  @mihai-macaneata

**Comment by melish** [comment]
There are some inconsistencies between the validation of the form and the input format.
Moreover, the input format of the field is not the same as specified on this ticked:

https://www.dropbox.com/s/3ide9dilduiptlh/2019-03-05%2011_17_33-Window.png?dl=0
