### ISSUE TITLE
As Secretariat, we need to be able to enter “Date of submission” manually

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#590]
When the Secretariat is entering the information, we need to be able to enter “Date of submission” manually (currently has three dots) – the date entry mechanism/interface can be similar to the “Date” field.  This field should only be automated when it is a Party submitting (in which case the field should not even be shown to the Parties until after they have clicked Submit).

**Comment by catalinjitea** [comment]
As a secretariat I should be able to edit "Date of submission" even after Submit.

**Comment by melish** [comment]
Please hold on, I will get more clarifications about the expected behaviour today.

**Comment by melish** [comment]
Date of submission should:
- not be visible to parties during Data Entry state (and be visible after submit).
- be visible, editable and mandatory for Secretariat users in any state

- be filled in automatically when a party submits

**Comment by sorinstelian** [comment]
Closed in https://github.com/eaudeweb/ozone/pull/619 and some subsequent commits
