### ISSUE TITLE
Postal address is limited to 64 characters.

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#591]
This is too low – can we make it 256 or something similar. Please make it a text area field.

**Comment by mihai-macaneata** [comment]
@sorinstelian Is there a limit in backend for the field ? If not, you can unassign yourself

**Comment by sorinstelian** [comment]
Funnily, we only have a "postal code" field, which is limited to 64 characters (which should be enough for a postal code). The question is: should we have both a "postal code" and a "postal address", or just a postal address? @nico4 ?

**Comment by sorinstelian** [comment]
@mihai-macaneata Added a "postal address" field in https://github.com/eaudeweb/ozone/pull/618

**Comment by nico4** [comment]
Delete postal code.

**Comment by nico4** [comment]
Be sure that you fixed  the old records https://www.dropbox.com/s/g05ydl9cggi2c6z/2019-02-14%2018_43_12-Window.png?dl=0

**Comment by mihai-macaneata** [comment]
Removed postal code from frontend on develop.
It should also be removed from backend.

**Comment by sorinstelian** [comment]
Removed postal code in https://github.com/eaudeweb/ozone/pull/639
