### ISSUE TITLE
The flag “Has blanks” can only be checked if the flag “Checked blanks” is checked.

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#594]
The flag “Has blanks” can only be checked if the flag “Checked blanks” is checked.  Similarly, the flag “Confirmed blanks” can only be checked if “Has blanks” is already checked.

The flags Has blanks/Checked blanks/Confirmed blanks are only relevant for the secretariat, when entering submissions received via other channels (e.g. mail).

Hence, these checkboxes should be hidden for parties.
The secretariat will be able to set them when pressing Submit, in the modal confirmation dialog (see #643). But they will also be able to change the flags afterwards (in any state), because confirmation from parties may come later in the process.

Since each flag depends on the previous one being set, please implement this behaviour:
- when Has blanks is set, automatically set Has blanks (if not already set)
- when Confirmed blanks is set, automatically set Checked/Has blanks
- when Checked blanks is cleared, automatically clear Has/Confirmed blanks
- when Has blanks is cleared, automatically clear Confirmed blanks

The same behaviour should be implemented in the modal dialog.

Validating/Changing these flags is not relevant for the backend.

**Comment by melish** [comment]
Flags related to blanks should only be visible in the UI when
- user is secretariat
- state is data entry

It's enough to implement the validation ("has blanks" conditioned by "checked blanks") in the frontend .
This flags are only needed when parties submit via alternative channels, not when submitting via the ORS (web forms) nor via the API.

Still not clear: will the secretariat wait for the confirmation of blanks before pressing Submit?

**Comment by nico4** [comment]
I was able to submit the "confirmed blanks" even if "checked blanks" was set to false.

**Comment by sorinstelian** [comment]
Fixed in https://github.com/eaudeweb/ozone/pull/824

Used message:
`Unable to confirm blanks if blanks are not checked first`
