### ISSUE TITLE
Questionnaire comments field

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#597]
We need a comments field at the bottom of the Questionnaire – similar to the other data forms.

**Comment by mihai-macaneata** [comment]
Assign me this ticket please after the backend part is done

**Comment by sorinstelian** [comment]
Following Art 7 flags were added in https://github.com/eaudeweb/ozone/pull/609:
- questionnaire_remarks_party
- questionnaire_remarks_secretariat
