### ISSUE TITLE
Remove unneeded remarks_os/secretariat fields from Submission

### ISSUE THREAD

**Issue by sorinstelian** [eaudeweb/ozone#612]
Also check that the serializers mixins that deal with remarks work as expected.

**LATER EDIT**: they do. :)

**Comment by sorinstelian** [comment]
Actually, these general remarks are used in historical submissions. For such cases, the old remarks data should probably be moved to the questionnaire remarks, but for now it is better to defer it until the OS makes a decision.

**Comment by melish** [comment]
Confirmed: we only need remarks under questionnaire.
The data import should be updated to use those instead of submission.remarks.
Then submission.remarks can be removed.
