### ISSUE TITLE
Serverside translation extraction is not working for some strings

### ISSUE THREAD

**Issue by danmisailescu** [eaudeweb/ozone#623]
Today, @nico4 sent me these pictures with missing translated texts for Russian language. Looking at the error I deduced it is a serverside problem.
For example in UserProfile.vue screen, EMAIL works but the others don't, even though all of them are taken from  $gettext. It seems these keys are missing from the Russian translation file, so they are not extracted correctly from the server.
https://cl.ly/fe27beeb8a2a

         <b-input-group class="mb-2" :prepend="$gettext('First name')">
            <input class="form-control" v-model="userProfile.first_name" />
        </b-input-group>
        <b-input-group class="mb-2" :prepend="$gettext('Last name')">
            <input class="form-control" v-model="userProfile.last_name" />
        </b-input-group>
        <b-input-group class="mb-2" :prepend="$gettext('Email')">
            <input class="form-control" v-model="userProfile.email" />
        </b-input-group>
        <b-input-group class="mb-2" :prepend="$gettext('Language')">
              ............
	</b-input-group>

I think the same problem is in the other printscreens

https://cl.ly/626e7dbe5119
https://cl.ly/d2142bee3cd1
https://cl.ly/fe5f3aa2e112
https://cl.ly/c4b27f4a5102
https://cl.ly/3ae90ced28a5
https://cl.ly/b8ffa1f75eb9

**Comment by alexkiro** [comment]
They are here (see translation [repo](https://github.com/eaudeweb/ozone-translations/blob/master/frontend/locale/ru/LC_MESSAGES/app.po#L2035), they just haven't had translated strings added.
