### ISSUE TITLE
DateReported wrong mapping

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#625]
when importing legacy data, DateReported should be mapped to submitted_at (not to SubmissionInfo.date_reported)

Related with #267

**Comment by melish** [comment]
Also, 
* Overall.Remarks should be stored in Questionnaire.remarks_os
* Overall.SubmissionType should be stored in SubmissionInfo.submission_format (see #595)

**Comment by catalinjitea** [comment]
Blocked because mapping is necessary for Overall.SubmissionType field.
