### ISSUE TITLE
Bug in dashboard available actions for RAF

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#629]
After pressing "Revise" for a RAF submission in state "submitted":

![image](https://user-images.githubusercontent.com/1218168/52840461-0aa82c80-3102-11e9-86d9-b89338cbfc2c.png)

And then after refreshing the page:

![2019-02-15 09_13_05-window](https://user-images.githubusercontent.com/1218168/52840491-1f84c000-3102-11e9-8237-c4c51cb7de1b.png)

**Comment by sorinstelian** [comment]
Also, right after Submitting the initial version (version 1), the dashboard shows it as editable, even though the `submissions/` endpoint is called and its response is correct (submission is not editable):
`{"url":"https://ozone-staging.edw.ro/api/submissions/28190/","id":28190,"party":29,"reporting_period":30,"obligation":2,"created_at":"2019-02-15","updated_at":"2019-02-15","submitted_at":"2019-02-15T10:48:30.787846+03:00","created_by":5,"last_edited_by":5,"filled_by_secretariat":true,"version":1,"current_state":"submitted","previous_state":"data_entry","data_changes_allowed":false,"is_current":true,"flag_provisional":false,"flag_valid":null,"available_transitions":["process","recall"],"is_cloneable":true,"can_edit_data":false}`
