### ISSUE TITLE
"Exemption" should not be visible in the list of obligations for parties

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#631]
Actually, it would be useful for parties to see them in the dashboard (all submissions), but not be allowed to create them.
Only the secretariat should see "Exemption" in the list of obligations from the "Create submission" box.

Also, a better name would be "Exemptions"

**Comment by sorinstelian** [comment]
@melish : The workflow described in https://github.com/eaudeweb/ozone/issues/536 does include Parties as potential users. Also, it seems like an easy, transparent way of linking party-submitted nominations with actual approvals. We will modify the workflow if that's what the OS wants, but then we need additional details about how it will work.

**Comment by melish** [comment]
Confirmed with OzSec - parties will use the Exemption form to upload files and view structured data entered by the secretariat.
