### ISSUE TITLE
Import of legacy exemptions

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#632]
From excel file: legacy_exemptions.xlsx
Two type of submissions should be created:

* submission for obligation "Exemption"
sheet EssenNom goes to the "Nomination" tab
sheet EssenExemp goes to the "Approved" tab

* submission for obligation "Essential and Critical uses (RAF)"
from sheet EssenUse

**Comment by melish** [comment]
Column/Field mapping:

Common
======
CntryId => party
PeriodId => period
SubstId => substance
DataID => ignore
UserCreate, UserUpdate, TS -> ignore
DateCreate, DateUpdate -> created_at, updated_at

EssenNom
=======
SubmitDate => submitted_at
SubmitAmt => quantity
Remark => remarks_os

EssenExemp
=========
ApprDec => decision_approved
ApprTEAP => needs new field
ApprAmt => quantity
Remark => remarks_os
TypeEssenCrit => needs new field
IsEmergency => needs new field

EssenUse/RAF.
==========
NB! there can be multiple rows in EssenUse for the same party/period/substance (because of ImpSrcCntryID) -  see CA/2005/194

ImpSrcCntryID -> import_party, i.e. country of (5) Amount acquired by import & countries of manufacture
AllowSameSrc -> ignore
Exempted -> quantity_exempted, i.e. (3) Amount exempted
Produced -> quantity_produced, i.e. (4) Amount acquired by production
Imported -> quantity_imported, i.e. (5) Amount acquired by import (by country, see ImpSrcCntryID)
OpenBal -> quantity_open_bal, i.e. (8) On hand start of the year
EssenUse -> quantity_essential_uses, i.e. (10) Used
Exported -> quantity_exported, i.e. (11) Amount exported
Destroyed -> quantity_destroyed, i.e. (12) Amount destroyed
Remark -> remarks_os (for each row). 

TBD:  should there be a row-level remark field + one tab-level remark field?

**Comment by sorinstelian** [comment]
`import_exemptions` command added in https://github.com/eaudeweb/ozone/pull/665
