### ISSUE TITLE
Remarks are saved even when questionnaire is not filled

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#636]
![2019-02-15 18_45_21-window](https://user-images.githubusercontent.com/1218168/52871127-06a3fb00-3152-11e9-995f-6b9ff99eb37e.png)

**Comment by melish** [comment]
Not sure if this is a bug or it's supposed to work like that.

**Comment by mihai-macaneata** [comment]
It's supposed to work like that, because we're not sure how it's supposed to work. To make the permissions implementation easier, remarks will always be saved if they can be edited.

**Comment by mihai-macaneata** [comment]
If you can edit a field, you can save the form.
This helps with cases when the secretariat wants to comment or change flags, but they don't have edit rights

**Comment by melish** [comment]
This issue is not valid anymore, as it will be allowed to save the submission even before choosing answers in the questionnaire.
