### ISSUE TITLE
"Clone" buttons missing from UI

### ISSUE THREAD

**Issue by sorinstelian** [eaudeweb/ozone#655]

**Comment by sorinstelian** [comment]
Even if some submissions have the `is_cloneable` flag set, there is no "Clone" button displayed for them. AFAIK this had already been implemented and was working.

**Comment by nico4** [comment]
* this might imply that cloning a submission in Data Entry should be allowed (if created by a different type of user (party/secretariat) than the other one)

Pe scurt, daca nu l-a facut altul si nu-l pot edita, trebuie sa-l pot clona, chiar daca sunt in data_entry. Vezi #642

**Comment by sorinstelian** [comment]
@danmisailescu : UI should simply take into account the `is_cloneable` flag present on each submission and either display the Clone button based on that.

**Comment by sorinstelian** [comment]
Backend part is already implemented, just need to remove restriction from UI.

**Comment by sorinstelian** [comment]
Actually, at cloning/revising, there is no restriction in the UI. The functionality already works as expected only with the backend changes. Will move the comment about `is_cloneable` and the UI to #642, as the problem only appears at creating new submissions from the "Create Submission" section. Closing.
