### ISSUE TITLE
"Finalize" button should be available in "Processing" state, even if valid flag not set

### ISSUE THREAD

**Issue by sorinstelian** [eaudeweb/ozone#662]
This means that "finalize" should be in the Submission's `available_transitions`.

This way, the user will be able to see and press the "Finalize" and be asked at that point whether the Submission is valid or not.

**Comment by sorinstelian** [comment]
In this case, the transition confirmation modal should probably include the question.

**Comment by sorinstelian** [comment]
Added backend changes so that the "Finalize" button now appears in the "Processing" state, even if `is_valid` is not set.

*Still to be implemented on frontend side:* the `valid` flag should be set to either True or False in the state transition modal.

**Comment by sorinstelian** [comment]
Added priority "Highest" as this is Article 7-related.

**Comment by melish** [comment]
Related to #643

**Comment by mihai-macaneata** [comment]
closed in #744
