### ISSUE TITLE
Sort obligations by id (asc) in "Create submission" dropdown

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#678]
There is no predefined order in the dropdown list. We need Art 7 to be first and to control the order.

**Comment by sorinstelian** [comment]
@melish : Right now the obligations already seem ordered by id. Perhaps we should use a different order in the fixtures?

**Comment by melish** [comment]
@sorinstelian it's not guaranteed (postgresql decides).
Check again https://ozone-staging.edw.ro/api/obligations/

**Comment by melish** [comment]
Sorting seems to be done by alphabetical order of ID's (10,11,1).
