### ISSUE TITLE
Re-numbering column headers (Art 7)

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#682]
Imports Tab
========
(1)          Annex/Group    
(2a)        Substance           
(2b)        Exporting party for quantities reported as imports
(3)          New
(4)          Recovered and reclaimed
(5)          Quantity of new substances imported as feedstock
(6)          Quantity
(7)          Decision / type of use or remark
Status column should not have a number."

Exports
============
A similar renumbering is proposed so that it matches (as closely as possible) with the approved forms.
1a)          Annex/Group
1b)         Substances
2)            Country of destination of exports
3)            New
4)            Recovered and reclaimed
5)            Quantity of new substances exported as feedstock
6)            Quantity
7)            Decision / type of use or remark
Status column should not have a number."

Destroy
=======
A similar renumbering is proposed so that it matches (as closely as possible) with the approved forms
1a)          Annex/Group
1b)         Substance
2)            Quantity destroyed
3a)          Remarks (party)
3b)         Remarks (secretariat)
Status column should not have a number."

Others
======
Similar checks and fixes should be done for the   numbering of columns on the other forms (e.g. Columns labelled “Group” should   be labelled “Annex/Group”, Status column should not have a number; “Remarks   Party” and “Remarks Secretariat” should have the same number – just that one   column is (a) and the other is (b).

**Comment by nico4** [comment]
(1) Annex/Group
(2a) Substance
(2b) Exporting party for quantities reported as imports

should be 

(1a) Annex/Group
(1b) Substance
(2) Exporting party for quantities reported as imports

to be in line with the other table columns.

**Comment by melish** [comment]
Please make the following updates (mainly for Art. 7 - Blends):
	Imports: (2a) instead of (2)
	Exports: (1a) instead of (1), (1b) instead of (2) Blend
	Destruction: (1a) instead of (1), (1b) instead of (2)
	Nonparty: remove "(" from Status column
	Emissions: replace D with d in "For Destruction"
