### ISSUE TITLE
We can submit without entering the submission info page, shouldn’t this be mandatory?

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#686]
WTF?

**Comment by melish** [comment]
Confirmed for a new (unsaved) submission.

**Comment by sorinstelian** [comment]
Will disable the `submit` transition if that info is not filled. Also if the questionnaire is not answered.

**Comment by melish** [comment]
Remember that we are migrating legacy data which doesn't have Submission info fields and also some uncompleted fields in the questionnaire.

**Comment by sorinstelian** [comment]
When migrating legacy data, the state is changed by directly altering the relevant model field, circumventing the transition checks that are performed when using the API.

**Comment by sorinstelian** [comment]
Changed condition to allow only one of email or address to be set
92bab202d7b3e4ed8b2054fd39c5c57d5cbca58b
