### ISSUE TITLE
Default value for reporting channel

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#688]
should be "Email" - but only when the secretariat is doing the data entry.

For party users, it should remain as it is (default = Web forms, read-only).

Extend the model with additional flags (is_default_party, is_default_secretariat), create an endpoint, then reassign issue to update frontend code so that it uses the endpoint (nowadays it's hardcoded in tabSubInfo.js)

**Comment by sorinstelian** [comment]
@mihai-macaneata : assigning to you, added `reporting_channel` field in the response from the `api/default-values/` endpoint.
