### ISSUE TITLE
Secretariat picking up a version in Data Entry state

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#7]
should it be allowed or should someone Submit it first?

**Comment by melish** [comment]
To confirm with OzSec:
- Secretariat cannot make changes to a version in data_entry state, created by parties
- Secretariat cannot submit, clone and delete it
- Secretariat cannot create a new version for the same period and obligation (because there is already one in data_entry)

**Comment by melish** [comment]
Administrators (OS.A, i.e. superuser accounts) should be able to delete any submission in data entry, even if they were created by parties.

**Comment by sorinstelian** [comment]
Created https://github.com/eaudeweb/ozone/issues/642 for the OzSec feedback request in https://github.com/eaudeweb/ozone/issues/7#issuecomment-463688418.

**Comment by sorinstelian** [comment]
Added latest OS superuser requirements in https://github.com/eaudeweb/ozone/issues/551, closing this issue.
