### ISSUE TITLE
Art.7 read-only fields after Submit

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#701]
In short: after submit, the only allowed changes should be:
- remarks
- files
- some flags: provisional and blanks-related

It should not be possible (for all roles) to make changes in:
- submission info (including reporting channel, reporting format, date of submission)
- "Reported in full" flags (by annex/group)
- questionnaire answers
- substances and quantities

Assigning to @sorinstelian for the backend part, please reassign afterwards for the front-end.

**Comment by sorinstelian** [comment]
Added requested changes in backend.

@mihai-macaneata : I think the only UI change needed is to take into account the `can_change_submitted_at` flag on the submission
