### ISSUE TITLE
Add status and changelog information to submission form

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#702]
Proposed: in the breadcrumb line, see below:

![image](https://user-images.githubusercontent.com/1218168/53979739-3b82ec80-4117-11e9-8143-04abdb353855.png)

**Comment by melish** [comment]
Also revise the layout of some flags:

![image](https://user-images.githubusercontent.com/1218168/54033697-ad157600-41bd-11e9-8545-e78046dda26c.png)

**Comment by mihai-macaneata** [comment]
closed in 70a22f43f7e2a469911247b487156969e6e3f460

**Comment by sorinstelian** [comment]
@mihai-macaneata : added `created_at` in submission detail in e41920917904715e1dd578876b2f255941da517f
