### ISSUE TITLE
Dashboard - All submissions - "Show all versions" checkbox

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#706]
In the list of submissions, for *all* periods (including the current ones), show:

- all submissions which are not superseded, if "All versions" is not checked
- all submissions, if "All versions" is checked

Notes:
* Use friendly names for statuses (i.e. "Data entry", not "data_entry")
* For superseded submissions, show "(Superseded)" after the status (in the same cell)
* Remember the default sort order as described on #699

**Comment by sorinstelian** [comment]
@mihai-macaneata : you can use the `is_superseded` URL parameter on the `submissions/` endpoint.
If set to `true`, will only show superseded submissions. If `false`, only non-superseded.

**Comment by nico4** [comment]
Not implemented:

* Use friendly names for statuses (i.e. "Data entry", not "data_entry")
* For superseded submissions, show "(Superseded)" after the status (in the same cell)
