### ISSUE TITLE
Error about Date of submission when trying to save

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#712]
Steps to reproduce:
As Party:
* Create a new submission (enter mandatory submission info and choose No for all answers in the questionnaire). 
* Submit

As Secretariat:
* Open the submission and press Process
* Note that Date of submission is still editable (until #701 is fixed)
* Without reloading the submission, press "Save and continue"

An error message appears:

![image](https://user-images.githubusercontent.com/1218168/54043479-59168b80-41d5-11e9-8760-fb42a1e4b9d5.png)

**Comment by sorinstelian** [comment]
`can_change_submitted_at` flag is already available on the `submissions/<pk>/` endpoint
