### ISSUE TITLE
Allow save even when the questionnaire is not filled

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#726]

**Comment by mihai-macaneata** [comment]
frontend part is done. The questionaire fields need to not be not null in backend.

**Comment by sorinstelian** [comment]
@melish: After latest backend changes (fa1b0bcb53c3afedf0d763a4a441d3cb83efb79b), current behavior is to show the "Submit" button even if no Questionnaire answers have been given; but actually pressing it will fail with the following error message:
```
All questionnaire answers must be filled before submitting!
```
