### ISSUE TITLE
File upload doesn't work anymore on staging

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#762]
HTTP 500: pre-create hook failed: Post http://app:8000/api/uploads/: EOF

when uploading a file to "Laboratory and analytical uses / China / 2018 / Version 1 (Data entry)"

**Comment by sorinstelian** [comment]
Solved on staging by updating Jenkins conf to add the following line in docker-compose.override.yml:
```
   tusd:
+    command: ["-dir", "/srv/tusd-data", "-hooks-http", "https://ozone-staging.edw.ro/api/uploads/"]
     ports:
```

**Comment by sorinstelian** [comment]
Also did the same for the prod deploy.
