### ISSUE TITLE
Duplicated rows after save + file upload

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#763]
Unable to reproduce for now. Possibly related to a retry made automatically during file upload (which is not working currently).
The duplicated records have been saved in the database.

A related error logged by the backend was:
```
POST /api/submissions/6048/token/
  File "./ozone/core/serializers.py", line 474, in update
    return super().update(instance, validated_data)
  File "./ozone/core/serializers.py", line 147, in update
    data_dictionary = self.construct_data_dictionary(validated_data)
  File "./ozone/core/serializers.py", line 95, in construct_data_dictionary
    raise ValidationError(_(f"Duplicate value for {field_value}"))
django.core.exceptions.ValidationError: ['Duplicate value for (<Substance: Methyl Bromide>, None)']
```

**Comment by sorinstelian** [comment]
It looks like the error is triggered by the initial POST (currently create() does not do any data checks). Not sure though how/why the UI sends the entries duplicated.

Will update create() to also check data, like update() does.

**Comment by sorinstelian** [comment]
Update: it seems like create() already checks the consistency of the data (though, if it's being called twice (two POSTs), it will not check whether the new data duplicates existing data). Investigated some more but could not find a root cause with the available information.
