### ISSUE TITLE
Default sort order in dashboard (all submissions)

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#767]
In all submissions records should be sorted by period (desc), not by last modified,
then by obligation (same order of obligations as in Create submission)

**Comment by sorinstelian** [comment]
I think this is more of a backend issue, will look at it.

**Comment by sorinstelian** [comment]
Added default ordering on the SubmissionViewSet as specified; however frontend does need changes as it uses specific ordering parameters when querying the API.

**Comment by melish** [comment]
To be re-tested.
