### ISSUE TITLE
Blend components are not stored in DB during import of legacy data

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#771]
I can see items with blend_id, but no items with blend_item_id after the import of legacy art. 7 submissions.

This is necessary later on, during data aggregation and calculation of derived data.

Related to #760

**Comment by sorinstelian** [comment]
This is because `bulk_create` is used to populate the submission's data tables. The model's save() method, which creates the derived substance rows is thus not called. We should use save() instead.
