### ISSUE TITLE
Discriminator field for HFC-23

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#781]
Since we will keep only one Annex Group (F) for both FI and FII, we should change:
- the groups fixture, to replace group_id ("F" instead of FI and FII)
- the mkfixtures code for substances to handle legacy data (FI, FII => F)
- to add a new boolean field called "is_captured" and set it to True only for "HFC-23" (from mkfixtures code)

**Comment by nico4** [comment]
Goes to @mihai-macaneata for frontend development.

**Comment by mihai-macaneata** [comment]
closed in 47a6368ef4a7dbb1195e527afc86f9fa97d09a4c
