### ISSUE TITLE
Production for supply to Article 5 countries TDB

### ISSUE THREAD

**Issue by mihai-macaneata** [eaudeweb/ozone#79]
Production - BDN (Production for supply to Article 5 countries) -  is enabled only for Annex C Group 1 but it depends in fact on the period and party type (see charts from Section 1.3 Handbook). Vom face un API pentru Limits (edited)

Andrei needs to talk to Sorin first

**Comment by melish** [comment]
As clarified today, we must allow reporters to enter data in BDN fields even if the applicable limit is zero.
In practice, the compliance checks for BDN limits are only done when the global calculated production/consumption is above the limit.

The same approach goes for the Essential/Critical use and other kind of limits.
