### ISSUE TITLE
IE11 issues

### ISSUE THREAD

**Issue by sboghy** [eaudeweb/ozone#796]
* [x] Newlines don't work for some tooltips:

![image](https://user-images.githubusercontent.com/1218168/57431972-215faa80-723d-11e9-9cd4-28504089798a.png)

* [x] Left menu not fully visible and misaligned:

![image](https://user-images.githubusercontent.com/1218168/60108410-39e63e80-9771-11e9-9129-586a740e56b8.png)

* [x] Add substances button is not visible:

![image](https://user-images.githubusercontent.com/1218168/60108532-6601bf80-9771-11e9-9e6b-67bde0379f99.png)

* [x] Date of submission field looks disabled, even when active:

![image](https://user-images.githubusercontent.com/1218168/60108662-a8c39780-9771-11e9-9883-ba81fae2d30a.png)
![image](https://user-images.githubusercontent.com/1218168/60108685-b6791d00-9771-11e9-9f30-5ada70d43e2c.png)

* [x] Clicking on the validation icon (![image](https://user-images.githubusercontent.com/1218168/60109203-a150be00-9772-11e9-80f6-1b8f58cfc2ed.png)) doesn't open the Validation tab. Delete doesn't seem to work, as well

* [x] Auto-logout doesn't work. The "Are you sure you want to leave this page" popup is blocking the logout process:

![image](https://user-images.githubusercontent.com/1218168/60115982-d3b4e800-977f-11e9-86b0-4699601aa2c4.png)

**Comment by mihai-macaneata** [comment]
> Clicking on the validation icon (image) doesn't open the Validation tab. Delete doesn't seem to work, as well

Can't reproduce
