### ISSUE TITLE
Django admin improvements

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#800]
Filters, search, sort-order, etc

**Comment by catalinjitea** [comment]
More improvements:

- As a secretariat I should be able to read/write data from Ozone Reporting Core admin section
- Meeting: search for location, filter by treaty_flag
- Obligation: help text for other and has_reporting_periods, display is_default
- SubmissionFormat: display is_default_party
- SubmissionInfo: see why it takes 24s to load a change page
- User: filter by party, is_secretariat and is_read_only

**Comment by melish** [comment]
Add `State` to list of submissions (in table and as a filter)

**Comment by melish** [comment]
Add PartyRatification in list of models

**Comment by catalinjitea** [comment]
Regarding
```
As a secretariat I should be able to read/write data from Ozone Reporting Core admin section
```
we decided to use Django built in Groups. We will create a group that has read/write permissions to Ozone Reporting Core section and we will add all secretariat users (with `is_staff` flag set to True) to this group.
