### ISSUE TITLE
Non party trade for Annex F

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#801]
For annex F substances, Non party trade is regulated only beginning with 2033.
This is not captured in control measures, so we were suggested a hardcoded constraint:

Only for parties, don't show in the list of annex groups and substances anything about Annex F

On the other hand, in case parties submit such data in hardcopy format, the secretariat should be able to capture the incorrect submission. One way to do it is through comments. The second alternative is to allow secretariat to enter anx F substances, but don't include those values in the calculation of production and consumption.

**Comment by sorinstelian** [comment]
As discussed with @mihai-macaneata , this will be implemented in the frontend.

**Comment by mihai-macaneata** [comment]
closed in 2f529c312e60f6c51ab094efb84480558e772e91
