### ISSUE TITLE
Essential vs Critical vs Emergency in RAF forms

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#803]
Related to #659 

We decided to have two different tables: 1) Essential 2) Critical. Remember that these tables have a different heading and calculation formula for field "On had at the end of the year".

When adding a substance, it will go either in the "Essential" table or in the "Critical" table based on the substance. Currently only uses of "Methyl Bromide" is Critical.

Emergency will be a checkbox displayed at the right of the table.

Users can set/clear "Emergency" field when adding substances or directly in the table, whichever is easier to implement.

**Comment by sorinstelian** [comment]
Backend side implemented in #815

**Comment by mihai-macaneata** [comment]
Getting an unexpected error when saving a substance for critical use.  Can you check it out @sorinstelian ?

**Comment by sorinstelian** [comment]
@mihai-macaneata: Fixed. Can we close this?
