### ISSUE TITLE
Validation rules for Exports and Imports

### ISSUE THREAD

**Issue by mihai-macaneata** [eaudeweb/ozone#81]
For Imports and Exports:
=================

For rows which have one country selected:

* [x] Either one of these three fields must exist: quantity_total_new , quantity_total_recovered, quantity_polyols
	ERR: "Total quantity imported for all uses is required."

* [x]  Sum(feedstock + total exempted + QPS for annex E) must be <= sum(total_new + total_recovered)
	total exempted = essential uses + critical uses + ... + other uses
	ERR: "Total quantity imported for all uses must be higher than the sum of individual components."

When there are rows without any country:

* [x] One extra validation is needed when party adds several rows for the same substance, some with country, one without any country, for instance party reports ExpNew and ExpRecov for each country, but the ExpFeedstock alltogether. The submission will therefore contain:
- one row for each country with some non-zero "total quantity exported for all uses" and zero feedstock
- one more row with zero "total quantity" but non-zero feedstock

In this case the validation becomes more complicated:
For rows which don't have a country the previous rule (total quantity >= sum of all components except polyol) does not apply anymore at row level. But at substance/blend level, the feedstock, essential, critical, etc. quantities should still be lower than the sum of all total quantities for the corresponding substance/blend (+qps for Annex E). Quantity_polyols are always excluded

**Comment by melish** [comment]
There are some more exceptions to be implemented, according to the latest clarifications received.
TODO andrei

**Comment by melish** [comment]
1) One extra validation is related to this scenario: party reports ExpNew and ExpRecov for each country, but the ExpFeedstock alltogether. The submission will therefore contain:
- one row for each country with some non-zero "total quantity exported for all uses" and zero feedstock
- one more row with zero "total quantity" but non-zero feedstock

In this case the validation becomes more complicated:
For rows which don't have a country the previous rule (total quantity >= sum of all components except polyol) does not apply anymore at row level. But at substance/blend level, the feedstock, essential, critical, etc. quantities should still be lower than the sum of all total quantities for the corresponding substance/blend. 

2) A second validation is related to the total number of rows in each tab. If user has selected Yes in the corresponding questionnaire, then it should not be allowed to *submit* with zero rows in the corresponding tab. Ideally we allow saving the form with zero rows, but not to submit it (show a list of errors when trying to submit). There will be also other warnings/confirmations shown when trying to submit, some of them involving a checkbox (similar to the "Accept terms and conditions" checkboxes), so the modal shown before submitting will be relatively complex, not just a simple Yes/No dialog.

**Comment by mihai-macaneata** [comment]
the branch for this is 81_country_validation

**Comment by sorinstelian** [comment]
Will implement this in the backend, as it is too complex for frontend.

**Comment by sorinstelian** [comment]
The complex validation across all data for imports/exports has been implemented in the backend.
