### ISSUE TITLE
Rounding rules for limits and derived amounts

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#812]
This rules apply to the calculation of baselines, limits and derived values: CalcProd, CalcCons, ProdArt5, Prod/Cons of LabUse, Prod/Imp of EssenUse, etc.

By default, all values are rounded to 1 decimal, with the exception of annex group C/I for (reporting period >= 2011 or special cases).

Special cases:
- reporting period 2009: parties CD, CG, DZ, EC, ER, GQ, GW, HT, LC, MA, MK, MZ, NE, NG, SZ, FJ, PK, PH
- reporting period 2010: parties DZ, EC, ER, HT, LC, LY, MA, NG, PE, SZ, TR, YE, FJ, PK, PH

When the baseline or limit refers to C/I and a period listed above, they must also have 2 decimals,

**Comment by sorinstelian** [comment]
Values should be kept like that in the DB, which means that given the variable number of decimals specified for different cases, the best way to ensure these rules is to override the save() methods of these models to perform the rounding.
