### ISSUE TITLE
New models to be implemented

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#813]
~PlansOfAction (Plans_of_Action, Plans_of_Action_Decs)~

~Deviation sources~
~DeviationTypes~
~ProdTransfers~

~Process Agents and related (ProcAgentContanTechnology, ProcAgentUses, ProcAgentEmitLimits, ProcAgentUsesValidity, ProcAgentEmitLimitsValidity, ProcAgentUsesReported)~

... to be continued

**Comment by melish** [comment]
TODO: models, fixtures and import of legacy data

**Comment by sorinstelian** [comment]
Implemented in da4a210cc0d263bc938e06197412711a7b4278f6

**Comment by melish** [comment]
Reopening, import of fixtures still not done

**Comment by sorinstelian** [comment]
`python manage.py import_plans_of_action <file_name>`
`python manage.py import_deviations <file_name>`
I did not upload the xlsx files to onedrive though. :)

**Comment by sorinstelian** [comment]
Uploaded them now.

**Comment by melish** [comment]
The are some records in the file having the same party/period/anx group, but isValid=TRUE and FALSE.
Only those having isValid=TRUE will be used in compliance reports, but there should still be a history of all invalidated benchmarks.

**Comment by sorinstelian** [comment]
Fixed import of plans of action and allowed records for the same party/period/group with is_valid True or False. However, there are still some duplicate records in the file (KP, group CI, 2018 to 2030, BA-2009-AI, MX-2009-BII). Should some of these be actually marked as not valid?

**Comment by sorinstelian** [comment]
Closing, as the models have been implemented. Will open a separate issue regarding import errors if needed (but the above-mentioned remaining issues had been caused by duplicate data).
