### ISSUE TITLE
API for the calculated derived values

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#816]
We must show in the frontend:
- in each Art 7 submission, a button which shows all derived values for the current party and period, in a modal table
- in the main menu, a table with all periods and all parties (for secretariat users) or pre-filtered (for parties)

The table has a row for each annex/group and the following columns:
- party, period (only in the dashboard)
- Annex/group
- CalcProd, CalcCons, ProdArt5
- BaselineProd, BaselineCons, BaselineBDN
- LimitProd, LimitCons, LimitBDN

**Comment by sorinstelian** [comment]
API added in https://github.com/eaudeweb/ozone/pull/817

**Comment by mihai-macaneata** [comment]
d78284e641c48005c04435d6e229efe69d0d3d12
05c2f9de7bae47bc6157a32d29b9091f46459aa9

**Comment by sorinstelian** [comment]
Closed on backed and frontend.

**Comment by nico4** [comment]
later edit, I was not on data entry.

**Comment by sorinstelian** [comment]
This is because only those "annex group reported" flags in the Submission Info tab have been checked.
