### ISSUE TITLE
Update make_test_users command

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#837]
related to #266 

* Set the "Staff status" flag to secretariat and secretariat_ro
* If possible create a superuser account (admin/admin)
* Create a group called "Secretariat" having all permissions for `core` models, except the "Can chart" permission
* Assign secretariat and secretariat_ro to this group
* Instead of party and party_ro, create one user for each (main) party. Username=password="party_{country code}" / party_{country code}_ro (for read-only) users
(country code in lowercase pls)

**Comment by catalinjitea** [comment]
```
If possible create a superuser account (admin/admin)
```
Already done in f8929637b8230052f8fcc197db8fb9d415f43b00.
