### ISSUE TITLE
Unable to activate account

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#838]
I created an user in the Django Admin, went to https://ozone-staging.edw.ro/mailtrap/ (mailtrap:mailtrap) and followed the instructions to activate my account. After completing the password fields (https://cl.ly/978414181c4a) the system generated the following error https://cl.ly/569f1af46105

The error in Sentry is https://sentry.io/share/issue/e1ff8718e51e41ac909122c50d5b23cb/

There are two tasks on this ticket:
 1) solve the problem
 2) build a nice error page on frontend.

**Comment by melish** [comment]
Not done: "build a nice error page on frontend." Please create a new ticket with more details for that.
