### ISSUE TITLE
Lookup tables improvements - Consumption

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#859]
- [ ] status for /reporting/lookup-tables/consumption
- [x] party dropdown - only main parties, no islands
- [x] rows to columns - by Limit type
- [x] move this to another submenu called "Reports" (instead of Lookup tables)

**Comment by sorinstelian** [comment]
What should be the name of the table? I suggest "Limits".

**Comment by sorinstelian** [comment]
What should a Party user see in this table? Only limits for his own Party or limits for all parties?

**Comment by melish** [comment]
> 
> 
> What should be the name of the table? I suggest "Limits".

The most relevant information here is the calculated production and consumption. I'll double check with the secretariat the title.

**Comment by melish** [comment]
> 
> 
> What should a Party user see in this table? Only limits for his own Party or limits for all parties?

Not sure, I'll check. It's likely that parties should only see their own data. However, the calculated amounts are public on the website, so maybe they would allow everyone to see them. Don't enforce filtering for now, just add a default filter by the current party (in the frontend)

**Comment by melish** [comment]
Better test this after #826

**Comment by melish** [comment]
Almost done, to be continued on #927 if needed
