### ISSUE TITLE
Attachments structure

### ISSUE THREAD

**Issue by mihai-macaneata** [eaudeweb/ozone#87]
Attachments:
        -> Columns: Filename(+ext), description (text field), size, date uploaded
        -> Should reject files without extensions. Implement some basic filtering based on the content type (e.g. filter out .exe, javascripts etc.)

**Comment by melish** [comment]
related to #98 and #88

**Comment by sorinstelian** [comment]
Solved in https://github.com/eaudeweb/ozone/pull/433
