### ISSUE TITLE
Add description in dropdown of Annex Groups

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#870]
When adding substances, in all forms, show the description of the annex group in brackets, after the name, e.g.:

"A/II (Halons)"

This might require a change in fixtures to update the name of all annex groups, i.e. "A/II" instead of "Annex A Group II" and also an update of /api/group-substances (to add the name and description).

**Comment by mihai-macaneata** [comment]
Assign me the ticket after you modify the fixutres, because at some point there was some hardcoded stuff regarding the annex groups.  Not sure if it's still the case, but it's better to double check
