### ISSUE TITLE
Confirmation for unsaved changes

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#871]
- unsaved changes are not detected when fields are changed in Submission Info or Questionnaire tab 

- When prompting to “Leave” page, please use the text “Leave this page” instead of “Leave” or “Leave Page”

- Use uppercase Y in "you have unsaved changes"

**Comment by mihai-macaneata** [comment]
closed in 4396d9ded841047ed556d28a59904e7d532ba37a

**Comment by nico4** [comment]
When I close the tab window and I have unsaved changes another pop dialog appears. https://www.loom.com/share/4601022372984c839b774b3ef67e272f 

Can we modify also this text?

**Comment by melish** [comment]
A window’s onbeforeunload property may be set to a function that returns a string that is shown to the user in a dialog box to confirm that the user wants to navigate away. This was intended to prevent users from losing data during navigation. Unfortunately, it is often used to scam users.

Starting in Chrome 51, a custom string will no longer be shown to the user. Chrome will still show a dialog to prevent users from losing data, but it's contents will be set by the browser instead of the web page.

With this change, Chrome will be consistent with Safari 9.1 and later, as well as Firefox 4 and later.
