### ISSUE TITLE
PDF export not opened in a new tab

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#879]
Related to OzSec feedback. To be reproduced and further investigated:

- [ ] 16.	For the Export to PDF – please ensure it is in a new window (my computer behaves OK – could not reproduce the problem on my computer).  However, on the demo computer, we viewed PDF, and then inadvertently closed the whole window.  It could be dependent on the browser together with the browser settings.

- [ ] 17.	When we closed the window by mistake, the system did not ask us to confirm that we wanted to exit.

**Comment by mihai-macaneata** [comment]
>  17.	When we closed the window by mistake, the system did not ask us to confirm that we wanted to exit.

Confirmation is required only if you are in a submission and there is an edited and unsaved field.

**Comment by melish** [comment]
Let's forget about this for now
