### ISSUE TITLE
Autosave of submission forms

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#880]
Related to:

- [ ] 19.	It was proposed to have an autosave implementation – saving every 5 minutes – so that if someone has been typing for long or leave the page for a while, they should not lose their work if electricity goes out – a common occurrence in developing countries.

Solution to be proposed.

**Comment by nico4** [comment]
Maybe we should have a notification instead. (e.g. Reminder: please save your submission)

**Comment by melish** [comment]
Replaced by #1059
