### ISSUE TITLE
Edit/Delete icons

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#883]
Let's try this alternative to edit/delete buttons:

- instead of showing them on mouseover, show the Edit icon (always) in the "Status" column
- Don't show any marker for "Valid" rows
- For invalid rows, show a small exclamation mark icon (red), with tooltip "Click here to see validation problems"
Suggested by the secretariat:
- Instead of delete row by row, show a checkbox (tooltip: select for deletion) which allows multiple selection and a "Delete X rows" button (only visible when some rows are selected).

**Comment by mihai-macaneata** [comment]
last part will be solved in #891
