### ISSUE TITLE
Content disposition header when downloaded attachments

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#885]
```
Content-Disposition: attachment; filename*=UTF-8''Oleksiy_D7-8%20Senior%20Fullstack%20Developer.pdf
```
doesn't seem right, the syntax is:
```
Content-Disposition: attachment; filename="filename.jpg"
```

**Comment by sorinstelian** [comment]
As per https://tools.ietf.org/html/rfc6266 (see section 4.3 and onwards), the syntax is actually correct; however as suggested in Annex D, we should probably also add `filename="..."` as a fallback for older browsers.

http://test.greenbytes.de/tech/tc2231/ also provides a very interesting overview of support for RFC 6626 in major browsers.

**Comment by sorinstelian** [comment]
Added the `filename` header as specified; don't think anything has to be done on the frontend side but will leave the issue open for now.

**Comment by mihai-macaneata** [comment]
Looks like it's working
