### ISSUE TITLE
Less padding in tables

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#895]
For instance, in table of blends, the type of blend wraps although there is enough white space to fit in one row:

![image](https://user-images.githubusercontent.com/1218168/56565313-c41af680-65b8-11e9-87d2-247351ff26c8.png)

**Comment by mihai-macaneata** [comment]
9258d32e96800fb942bc4d534d75d9676d9633e9

**Comment by melish** [comment]
Make "Azeotrope" not wrap on next row
