### ISSUE TITLE
Calculated consumption - different value

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#910]
For Japan/1997/EI, our calculated consumption is 2501 vs 3318 in the legacy table.
Ignoring process agent amounts (which are zero in this case), the formula is:

ProdAllNew-ProdFeedstock-ProdQuarAppl
-Destroyed
-ExpNew+ExpQuarAppl
+NPExport
+ImpNew-ImpFeedstock-ImpQuarAppl
(-ImpProcAgent-ProdProcAgent)

**Comment by sorinstelian** [comment]
Solved in #903
