### ISSUE TITLE
Secretariat should be able to directly Finalize an Exemption from initial_state

### ISSUE THREAD

**Issue by sorinstelian** [eaudeweb/ozone#921]
By setting the "emergency" flag.

**Comment by catalinjitea** [comment]
For this we can use the accelerated workflow.

Can we instantiate all submissions created by secretariat with accelerated workflow?

**Comment by sorinstelian** [comment]
I think we can, but we should also talk to @mihai-macaneata to see what the frontend implications are.

**Comment by sorinstelian** [comment]
Decided that OS should first move the "Data Entry" Submission to "Submitted" (optionally adding an attachment), then (if applicable) enter the Nomination and/or Approved data, then move the submisison to "Finalized".
