### ISSUE TITLE
Rounding issues v3

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#923]
See Norway/2004/AII - Destroyed 6.85 tons of HALON-1211 (A/II)
The ODP factor is 3.0
```
>>> 6.85*3.0
20.549999999999997
>>> float(decimal.Decimal(6.85)*decimal.Decimal(3.0))
20.55
```
Hence the calculated production rounded to 1 decimal is -20.5 instead of -20.6

Similar, but a bit more complex, for Ukraine/1997/BIII, production-feedstock of Carbon Tetrachloride:
```
>>> 6308.5*1.1-9117.9
-2178.5499999999993
```

**Comment by sorinstelian** [comment]
Closed in https://github.com/eaudeweb/ozone/pull/924
