### ISSUE TITLE
Migration of transfers legacy data

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#925]
Source tables: ProdTransfers, Letters, ProdTransfersLetters (mapping table between the first two)
Destination tables: Submission, SubmissionInfo, Transfer

Field mapping: 
LetterSenderCntryID => ignore
LetterDate => SubmissionInfo.DateReported and Submission.submitted_at
LetterSubject => ignore?
Letter.Remarks => a new field in Submission, or restructure the current *_remarks fields

ProdTransfers:
SubstId => Substance fk
PeriodID => Period
Annex, Group => ignore
DescSubstance => ignore?
ProdTransfer => transferred_amount
ProdTransferUsed =>used_amount
IsBDN => is_basic_domestic_need
SrcCntryID => Party FK and SubmissionInfo.Country
DestCntryID => destination_party
Remarks => RemarksSecretariat? (field does not exist yet, must be added in model)
'P' => transfer_type

*Notes*: 
1) there may be letters containing data for multiple periods. In this case, we should create multiple submissions, one for each period

2) when importing transfers, the aggregation table (ProdCons.prod_transfer) must be updated. Depending whether Art 7 submissions have been already imported or not, a record may or may not exist in table ProdCons

3) We don't have yet a UI for viewing the transfers.

**Comment by catalinjitea** [comment]
```
Remarks => RemarksSecretariat? (field does not exist yet, must be added in model)
```
No need for a new field, we already have `remarks_os`.

**Comment by sorinstelian** [comment]
Closed in #943

**Comment by melish** [comment]
I can see one issue in the migrated data: for instance, transfers 100005-100015 between US and other parties are recorded in ProdTransfers for period = 1994, while the submission has period = 2015 (the date of the letter).

I think it's correct to keep the letter date as "submission date", but the actual period should be the one from ProdTransfers - which might involve splitting up the records into multiple submissions (even if they have been reported in the same letter).

**Comment by melish** [comment]
Another (minor) issue is the submission status. The reported transfers are already processed and finalized - so the current state of the migrated data should be the final one.

**Comment by sorinstelian** [comment]
> Another (minor) issue is the submission status. The reported transfers are already processed and finalized - so the current state of the migrated data should be the final one.

Added a "Finalized" state to the Transfers (and Procagents) workflow and changed the import scripts to set all imported submissions to it.

**Comment by sorinstelian** [comment]
Regarding the occasional mismatch between Submission period and Transfer period, I would keep things as they are now. I think the cleanest way would be to have a Letter (with a submission date) that can have multiple Submissions, but that might be a bit too cumbersome and probably unlike what happens IRL.

Also, in future reporting, it may well be that a Submission reports Transfers from different periods.

**Comment by sorinstelian** [comment]
Closing for now, will open separate issue if OS doesn't agree with the idea above.
