### ISSUE TITLE
ProdCons table does not work well when logged in as party

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#927]
Filtering issues in /reporting/reports/production-consumption (which uses /api/aggregations/)

* [x] Reporting periods should ideally contain only existing values. If not possible, show only periods having reporting_allowed=True
* [x] Use the same sort order for period filter as in dashboard (C2001 between 2001 and 2000)
* [x] Sort data by default by: Period (desc), Party (asc), Annex/Group (asc)
* [x] Fix this: log in as party, change Reporting period to None (show all), change Party to None (show all) => the filters are now reset to the default

**Comment by sorinstelian** [comment]
Backend part done in https://github.com/eaudeweb/ozone/pull/930/files

Now party users can access aggregation data for other parties.

**Comment by razvanMiu** [comment]
We need an endpoint only with periods that have submissions.

**Comment by melish** [comment]
> We need an endpoint only with periods that have submissions.

Until then, you can show only periods having reporting_allowed=True

**Comment by razvanMiu** [comment]
https://github.com/eaudeweb/ozone/pull/967/commits/4588ef74095125b46fcecf2cffd48e6236905657
https://github.com/eaudeweb/ozone/pull/967/commits/ee20511f4be496115270adcda92a7a17908b24c1
