### ISSUE TITLE
Extend the "Transfers of production rights" form

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#931]
To show (read-only) the related structured data entered by the secretariat in the transfer forms.

**Comment by mihai-macaneata** [comment]
dc39549171dcfe99f99b9d020c14d45754f3b940

**Comment by melish** [comment]
Remaining:

- show names instead of ID's
![image](https://user-images.githubusercontent.com/1218168/59290349-025f9880-8c81-11e9-9aac-89365cccb737.png)

- it's save to remove the "Substances" heading, blends are not applicable in these forms

**Comment by melish** [comment]
- [ ] Right align amount
- [ ] Center align reporting period
- [ ] Replace "Transfer type" code with name (P=Production, C=Consumption)

**Comment by mihai-macaneata** [comment]
d9662a86197dff6b1c892f478f556cd89a7495c3
