### ISSUE TITLE
OzSec feedback for RAF forms

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#935]
* [x] 1.	For the first column, replace the “Annex Group” with “Year”, label it as column A.  This will match better with the approved form.
* [x] 2.	Label for column K should be “Quantity contained in exported product” – there is a semantic difference between Critical uses and the Essential use forms.  The same correction should be made when the edit dialog opens up.  
* [x] 3.	Amount exempted should not be filled manually – it should be extracted/calculated from the table EssenExemp.  The approval can be from more than one decision and more than one year.
@sorinstelian This point needs its own ticket - see #940

* [x] 4.	Label for column J may be too short – please make it “Used for essential use”
* [x] 5.	The critical use form letters (A, B, C, etc) are incorrect – kindly match column letters/numbering with the approved forms – The substance column should not there because critical uses only apply to MeBr – you have already implemented that aspect when adding substances.

* [x] Fix typo: "depletig"

* [x] In Edit popup, hide the "Cancel" button (near Add countries) unless substances are selected but not added yet

* [x] 'Emergency' checkbox doesn't have a label:
![image](https://user-images.githubusercontent.com/1218168/57443273-57f5ef00-7256-11e9-8e6d-97bcffc2093e.png)

* [x] Hide the "Export as PDF" button

**Comment by melish** [comment]
![RAF - essential other than lab](https://user-images.githubusercontent.com/1218168/57439681-334a4900-724f-11e9-9e55-c5b95f105026.png)
![RAF - critical MeBr](https://user-images.githubusercontent.com/1218168/57439688-35140c80-724f-11e9-9fde-7f15c7a89cef.png)

**Comment by mihai-macaneata** [comment]
4653bff38f350021ee78ac95144f5e14513c692c

**Comment by sorinstelian** [comment]
Removed assignment as exempted amount is now computed backend-side.
