### ISSUE TITLE
Approved amount for RAF

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#940]
Related to #935 and #939 
The approved amount should be calculated automatically based on approved exemptions (by summing ApprAmt per party, period and substance).

ATTN: Emergency exemptions should not be mixed with the normal exemptions.
In case there are both, two rows should be added in the RAF form -> This also requires changes in the frontend, to allow the same substance twice (one emergency, one non-emergency).

**Comment by sorinstelian** [comment]
On the backend side, quantity_exempted field is now read-only (implemented in https://github.com/eaudeweb/ozone/pull/968). Its value is 0 if no exemptions have been found for the party/period/substance; else it is a sum of all exempted quantities.

For emergency rows, only emergency exemptions are taken into account for its calculation. For non-emergency rows, only non-emergency exemptions.

**Comment by sorinstelian** [comment]
Did the following on the backend side (in https://github.com/eaudeweb/ozone/pull/992):
- made quantity_exempted editable again in RAF
- added endpoint to return emergency and non-emergency exempted amounts:
  `api/parties/<party_id>/approved_exemptions/?period=<period_id>`

**Comment by mihai-macaneata** [comment]
TODO:
Limit substance per table is 2. One with emergency and one without.
Automatically complete exempted field on add and emergency flag change
Validation for no multiple entries for a substance with the same flag.
