### ISSUE TITLE
Reporting vs control treaty id in groups

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#965]
In annex group model:
- TreatyIDReport defines which treaty imposes the "Reporting" obligation
- TreatyIDControl defines which treaty imposes the "Control Measures".

This means that:
- For finding out which are the non-parties, TreatyIDControl (?)
- For finding out which annex groups must be reported for a given period ("has reported in full" checkboxes), use TreatyIDReport.
- When checking possible non-compliances, use TreatyIDControl to obtain the annex groups covered.
- When calculating production and consumption, use only the annex groups checked as "reported in full".

**Comment by sorinstelian** [comment]
Closed in #966
