### ISSUE TITLE
Validation rules - to test

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#975]
Article 7 - US - 2015 - Exports
There is a validation error about MeBr (QPS amount) which should not exist.

(staging)/reporting/submission/art7?submission=https%3A%2F%2Fozone-staging.edw.ro%2Fapi%2Fsubmissions%2F29175%2F

**Comment by mihai-macaneata** [comment]
Validation is fixed in frontend, but the same validation seems to fail in backend when saving
