### ISSUE TITLE
Don't re-sort by ordering_id when pre-filling art 7 form

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#977]
Based on this rule:
1) by order of annex groups
2) by sort_order of substances (or blends, if it's a blend)

This means that the order will change when reloading the submission.
It also means that the order will have to be recomputed on each save,

**Comment by mihai-macaneata** [comment]
This shouldn't need any implementation in frontend

**Comment by melish** [comment]
Implemented in 64f7e6e2e2800280ffcfe88fff1d44587c82d455. 
Fixtures still to be updated, so that sort_order is global for all annex groups.
