### ISSUE TITLE
SubmissionInfo.country - model vs CharField

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#981]
SubmissionInfo.country is now a CharField, while the frontend treats it as a fk field to the Party model.

Make sure the implementation is consistent with the frontend (country is a dropdown of parties), with the legacy data migration scripts and with the PDF exports.

**Comment by catalinjitea** [comment]
Solved in #1005. 

It shouldn't affect the frontend, but @mihai-macaneata please double-check.

After that we can close this issue.

**Comment by melish** [comment]
Reassign to me when this is finished,
