### ISSUE TITLE
Allow enabling/disabling obligations in "create submission"

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#986]
HAT submissions won't be necessary until 2024, thus it would be better to hide them from the dropdown until the date.

**Comment by melish** [comment]
is_active should also be added in /api/obligations, to be interpreted in the UI (Dashboard->Create submission)

**Comment by sorinstelian** [comment]
`is_active` added to Obligation admin in 082fe4236871db4b68ce547100899d00d806a426 and to API in 0af87e07.

**Comment by sorinstelian** [comment]
UI should now filter obligations based on `is_active` - i.e. only allow the active ones to be used.
