### ISSUE TITLE
Look and feel for the login page

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#988]
See https://we.tl/t-2iSJNiN3FW
There are two background photos. Please pick the one which fits best, then we make a demo and decide whether it remains or replaced with the other image.

**Comment by razvanMiu** [comment]
https://github.com/eaudeweb/ozone/commit/b9c5944292f50c3491b2b84c534a5af395f8c777 -> We don't know in which folder to put the background image.

**Comment by sorinstelian** [comment]
Backend part solved in 517d46126896048adfa655d84c9225cfe3c47af1 .

Any general static content (that is not tied to a particular app) can now be placed in `PROJECT_ROOT/ozone/static` (including its subdirs) and can be accessed like:

`url("{% static '<path_relative_to_above_location>' %}")`
e.g. the path to use above for PROJECT_ROOT/ozone/static/images/bg.png should be `images/bg`.

**Comment by melish** [comment]
Fixed in #1011
