### ISSUE TITLE
API for reports

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#997]
We will have a number of reports (5-10) with various parameters, some of them multiple and/or optional.

e.g. The first one is the ProdCons report by period and party (e.g. 1) one period and one party - similar to the current ProdCons PDF export, 2) one period and multiple parties - one page for each party or 3) one party and multiple periods - one page for each period).

The first task is to define an API endpoint which lists the available reports, so that user can select one report from this list in the UI. It doesn't have to be a DB model, it can be an enum in the backend source code.
Think also about a way to model input parameters ( cardinality, optional/mandatory, etc.) and endpoint for each report (e.g. /api/reports/prodcons).

Next - create a directory structure in core.api.export_pdf.reports, so it's easy to add the actual implementation for each report. Then refactor the ProdCons report (others.py) so that the same backend code works for both the general report in the reports section and for "Export PDF" button from the submission page - Production and consumption modal dialog.

**Comment by catalinjitea** [comment]
close in #1004
